### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by sejalvasan** [nilisha-jais/Musicophilia#1]
An About page that describes the essence of the website. 
The thought process that went behind Musicophilia, the impact of this website on the user. 
Importance of music and dance on an everyday basis, and how it makes everything better. 
All the important information, along with pictures to make the content look more interesting and interactive.

**Comment by sejalvasan** [comment]
Can I please work on this issue?

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by nilisha-jais** [comment]
Hey @sejalvasan and @Jagannath8 you people can surely work on the issue but the coding phase starts from 10th onwards. Have patience till then. I'll be even adding new issues by the end of this week.

**Comment by sejalvasan** [comment]
> Hey @sejalvasan and @Jagannath8 you people can surely work on the issue but the coding phase starts from 10th onwards. Have patience till then. I'll be even adding new issues by the end of this week.
>
>>Okay, got it. Thanks.

**Comment by Swarnava77** [comment]
Hello Ma'am, please assign me this work. I am ready to contribute in other issues too.

**Comment by rvandana193** [comment]
Hlo mam, I would like to contribute in this issue. Please assign me this under LGM-SOC

**Comment by niloysikdar** [comment]
Hey @rvandana193 , you can start working on the issue.

**Comment by akitiashritha** [comment]
Hi, i am interested in contributing to either about us page or contact us page please assign  anything is fine.
