### ISSUE TITLE
Adding background in piano 

### ISSUE THREAD

**Issue by akshatvirmani** [nilisha-jais/Musicophilia#10]
I would like to work on this issue. Please assign this to me under LGM SOC.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by RakeshCharpe** [comment]
I would like to work on this issue under LCM Soc21.

**Comment by akshatvirmani** [comment]
Can I work on this issue?

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Sumit11081996** [comment]
@nilisha-jais can you assign me this issue
