### ISSUE TITLE
In band page add text glow effect on Band context .

### ISSUE THREAD

**Issue by starrohan999** [nilisha-jais/Musicophilia#103]
## 🚀 Feature

In the Band Page, we can add a glowing effect in the band context that suits website Ui {Green and pale green color are used}.

## Add relevant screenshot or video (if any)

The output should like this only glow effect is added no font family is changed.
![2021-06-11 (3)](https://user-images.githubusercontent.com/71714344/121648674-635f1880-cab5-11eb-84e8-0e1a19facc8b.png)

**Comment by starrohan999** [comment]
@niloysikdar  and @nilisha-jais  please look at this feature.
please assign it to me

**Comment by starrohan999** [comment]
hey @niloysikdar  please look at this feature.

**Comment by Ayushi7456** [comment]
Can i work on this if no one is assigned?

**Comment by starrohan999** [comment]
Hey, @niloysikdar please look at this issue.

**Comment by niloysikdar** [comment]
@nilisha-jais will it add more value to the website ? If so, you can go ahead @starrohan999

**Comment by starrohan999** [comment]
Ok sure @niloysikdar, @nilisha-jais please tell us whether it is putting more value on the website or not?

**Comment by nilisha-jais** [comment]
Somebody is working on the UI of the band....Anyways go ahead @starrohan999
