### ISSUE TITLE
Add guitar music instrument

### ISSUE THREAD

**Issue by vimalprogrammer** [nilisha-jais/Musicophilia#108]
## 🚀 Feature

Add a guitar music instrument under the Mindfull music section.

## Pitch

The guitar is a fretted musical instrument that typically has five or six strings. It is held flat against the player's body and played by strumming or plucking the strings with the dominant hand, while simultaneously pressing the strings against frets with the fingers of the opposite hand.
Tools used : HTML, CSS, JavaScript

## Add relevant screenshot or video (if any)
<h2>References</h2>

![download (1)](https://user-images.githubusercontent.com/76787061/121656588-43335780-cabd-11eb-8337-9bdd94e3ee3b.png)
![download (2)](https://user-images.githubusercontent.com/76787061/121656827-8392d580-cabd-11eb-85ad-491eaf160b5b.png)

I would like to work on this issue under LGMSOC, please assign me...

**Comment by nilisha-jais** [comment]
Go ahead @vimalprogrammer !

**Comment by vimalprogrammer** [comment]
@nilisha-jais Is any slack or discord channel available for this project for discussions, if yes please let me know...
