### ISSUE TITLE
Adding more instruments in band

### ISSUE THREAD

**Issue by akshatvirmani** [nilisha-jais/Musicophilia#11]
I would like to work on this issue. Please assign this to me under LGM SOC.

**Comment by Anuradha0501** [comment]
I would like to work on this issue as LGM Soc participant

**Comment by nilisha-jais** [comment]
Hey @akshatvirmani which instruments would you like to add

**Comment by nandinimalik16** [comment]
I would like to work on this issue as LGM Soc participant

**Comment by akshatvirmani** [comment]
@nilisha-jais I would like to add guitar, violin and other instruments.

**Comment by jugeshraghav** [comment]
I would like to work on the issue. along with adding new instruments in the drum I will make it play with the keyboard keys.
