### ISSUE TITLE
readme update required 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [nilisha-jais/Musicophilia#110]

**Comment by Ayan-thecodeking** [comment]
want to add contributers section in readme
 please assign me for this

**Comment by nilisha-jais** [comment]
@Ayan-thecodeking you need to make the following changes changes
-In the readme file "The Contribution Guidelines" should be short and without describing images
-Add a section of project maintainers

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking you need to make the following changes changes
> -In the readme file "The Contribution Guidelines" should be short and without describing images
> -Add a section of project maintainers

ok @nilisha-jais  @niloysikdar thank you :)
