### ISSUE TITLE
Add a contribution.md file

### ISSUE THREAD

**Issue by nilisha-jais** [nilisha-jais/Musicophilia#113]
## 📚 Documentation

(A clear and concise description of what the issue is.)
Create a simple contribution.md file which will help beginners to create a PR
Use this for <a href="https://github.com/nilisha-jais/CollegeAada/blob/main/CONTRIBUTION.md">reference </a>
But all photos will be of current project

**Comment by jugeshraghav** [comment]
I would like to work on the issue. Please get it assigned to me @nilisha-jais

**Comment by nilisha-jais** [comment]
Go ahead @jugeshraghav

**Comment by Salonee-Jain** [comment]
Can I work on this issue under LGM SOC

**Comment by jugeshraghav** [comment]
I am already working on this issue. 😇
