### ISSUE TITLE
Style memory game page

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [nilisha-jais/Musicophilia#115]
I would  like to update the memory game home page by adding CSS to it. @nilisha-jais Please assign me this under LGM-SOC'21.

**Comment by nilisha-jais** [comment]
Hey @Sukhseerat-Kaur your issue is same as #95 .So it would be better if you don't start working on it now. After the issue #95 is solved, if you like to do further enhancement open an issue in that case :)
