### ISSUE TITLE
Updating the images of memory game

### ISSUE THREAD

**Issue by akshatvirmani** [nilisha-jais/Musicophilia#12]
I would like to work on this issue. Please assign this to me under LGM SOC.

**Comment by nilisha-jais** [comment]
Hey @akshatvirmani the coding phase begins from 10th.I'll assign you then, till then have patience

**Comment by akshatvirmani** [comment]
Okay

**Comment by RR-Sahoo** [comment]
Hey, can I work on this issue..

**Comment by rvandana193** [comment]
Hey, I would like to work on this issue. Please assign this to me under LGM SOC.

**Comment by akshatvirmani** [comment]
Can I work on this issue?

**Comment by nilisha-jais** [comment]
@akshatvirmani go ahead. Assigning you
But remember don't change the dimensions of the image otherwise you need to change the code also

**Comment by niloysikdar** [comment]
Unassigned you from the issue @akshatvirmani

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by niloysikdar** [comment]
Assigned @Jagannath8 , go ahead
