### ISSUE TITLE
Changes in Site 

### ISSUE THREAD

**Issue by Anubhavdevv** [nilisha-jais/Musicophilia#121]
## 🚀 Feature

1)change the title μSICOPHILIA and replace it with MusicClub
2)Make the site responsive(Nav Bar)
## Motivation

I need to go over the site and make changes so that it can offer value to the lives of those that frequent it.

## Pitch
If it becomes more responsive, more traffic will be attracted to the site, and if we give it a catchy name, it will also attract people.

/assign

**Comment by mdinesh124** [comment]
@niloysikdar Please assign this issue to me under LGMSOC.

**Comment by Anubhavdevv** [comment]
thank you for assigning this to me 
:)

**Comment by harshita2216** [comment]
@nilisha-jais, please check if we need these changes or not. Thanks.
