### ISSUE TITLE
Adding tabla as an instrument 

### ISSUE THREAD

**Issue by nisha331** [nilisha-jais/Musicophilia#123]
## 🚀 Feature

I would like to add tabla in the list of musical instrument , the 2 tabla  has different sound "dhe" and "ta" it would be played when we click on respective tabla having the respective sound.

If you feel it would be good for the website I as a participant of LGMSOC would like to work on it , kindly assign it to me.

**Comment by nilisha-jais** [comment]
Assigning @nisha331
