### ISSUE TITLE
Consistency of site

### ISSUE THREAD

**Issue by Anupam-Panwar** [nilisha-jais/Musicophilia#13]
* Navbar and footer is not present in every page of the website.
* It will help user to navigate to other pages in website more easily.

![image](https://user-images.githubusercontent.com/65714751/120747560-d51bed00-c51e-11eb-971e-64031292b336.png)

* I would like to work on this.

**Comment by nitishapiplani** [comment]
I would like to work on this

**Comment by nandinimalik16** [comment]
I would like to work on this issue as LGM Soc participant

**Comment by Anupam-Panwar** [comment]
> * Navbar and footer is not present in every page of the website.
> * It will help user to navigate to other pages in website more easily.
> 
> ![image](https://user-images.githubusercontent.com/65714751/120747560-d51bed00-c51e-11eb-971e-64031292b336.png)
> 
> * I would like to work on this.

I would like to work on this issue
I am LGM Soc participant

**Comment by aum-singhal** [comment]
Hello Mam.

I will be happy to contribute in this issue.
If possible please assign it to me.
I am a participant of LGM-SOC

Thanks in advance 😊
