### ISSUE TITLE
Hovering Effect

### ISSUE THREAD

**Issue by anushka-srivastava22** [nilisha-jais/Musicophilia#130]
## 🚀 Feature
In the band page , I would like to add hovering effect of zoom out with box shadow

**Comment by anushka-srivastava22** [comment]
**/assign** 
I am a lgmsoc participant. 
In band page , I would like to contribute by adding zoom out with box shadow.
Kindly assign this issue to me under LGMSOC 21. Please..

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

**Comment by niloysikdar** [comment]
Assigned @anushka-srivastava22 , go ahead.
