### ISSUE TITLE
Recreate navbar

### ISSUE THREAD

**Issue by sameer2403** [nilisha-jais/Musicophilia#131]
## 🚀 Feature

1.add login and signup button
2.align navbar to the left of screen vertically

## Motivation

i have seen others music app and they have quite interesting navbar .

## Pitch

It will be responsive and eyecatching to the user.

## Add relevant screenshot or video (if any)

![screencapture-open-spotify-2021-06-11-23_29_19](https://user-images.githubusercontent.com/76219383/121730655-9cc37280-cb0d-11eb-8d51-a3f729c76328.png)

**Comment by sameer2403** [comment]
please assign it to me.

**Comment by niloysikdar** [comment]
Hey @sameer2403 , have you done any progress ?

**Comment by ashana1647** [comment]
please assign me this issue under LGMSOC21

**Comment by sameer2403** [comment]
> Hey @sameer2403 , have you done any progress ?

No ,please unassign me

**Comment by niloysikdar** [comment]
Assigned @ashana1647

**Comment by nitishapiplani** [comment]
can i work on this you can take best design

**Comment by padmajabhol** [comment]
Interested if this is still open.

**Comment by niloysikdar** [comment]
Sure @padmajabhol , waiting to see some significant changes from your side.

**Comment by harshita2216** [comment]
Any progress on this, @padmajabhol?

**Comment by padmajabhol** [comment]
> Any progress on this, @padmajabhol?

Yes, I m working on it, was a bit unwell. Will send the PR by tonight!

**Comment by harshita2216** [comment]
@padmajabhol, no problem. Please take your time. Take care! 😊
