### ISSUE TITLE
Common background for each level in the memory game

### ISSUE THREAD

**Issue by Amit-45** [nilisha-jais/Musicophilia#135]
Issue : The background of each level (easy , medium ,  hard)is black .
Changes that can be made : A common image background to each of the levels that would make the pages look interactive .
![Screenshot (170)](https://user-images.githubusercontent.com/77204104/121742594-a8b73080-cb1d-11eb-85dc-021e3a4e31ba.png)

**Comment by Amit-45** [comment]
Please assign me this issue under LGMSOC'21 .

**Comment by niloysikdar** [comment]
Assigned @Amit-45 , go ahead.
