### ISSUE TITLE
[Enhancement] Contact Us Page

### ISSUE THREAD

**Issue by niloysikdar** [nilisha-jais/Musicophilia#139]
## 🚀 Feature

The Contact Us page isn't matching with the website's current theme. Please make it similar.

**Comment by RiyaGupta89** [comment]
I can create a good interactive contact us page. Please assign me this issue.

**Comment by jugeshraghav** [comment]
Hi! Can I work on this issue.

**Comment by royalleads15** [comment]
@niloysikdar I am ready for that !

**Comment by niloysikdar** [comment]
Assigned @RiyaGupta89 , go ahead.

**Comment by RiyaGupta89** [comment]
Uh, hey. You have not labeled any level to this issue?

**Comment by niloysikdar** [comment]
Hey @RiyaGupta89 , we will add levels in the pr according to your work. Like if you use bootstrap instead of your own CSS then obviously we will assign a low level.

**Comment by RiyaGupta89** [comment]
![ui-contact-page](https://user-images.githubusercontent.com/72425181/121810576-16c73900-cc7f-11eb-87d7-ac6bab870a59.png)

Please see if you like the UI, I used CSS only! No CSS frameworks are being used.

**Comment by RiyaGupta89** [comment]
![ui-phone](https://user-images.githubusercontent.com/72425181/121811099-dff22280-cc80-11eb-816c-61f26c4b4308.png)
![ui-phone1](https://user-images.githubusercontent.com/72425181/121811102-e2547c80-cc80-11eb-9265-b7a85d0c78b9.png)
This is how it looks on phone, tell me if you want any changes in the UI. Also, you would prefer logo's "u" white or green?

**Comment by RiyaGupta89** [comment]
Can I please get a response?

**Comment by niloysikdar** [comment]
Sorry @RiyaGupta89 , I forgot your comment in this vast number of issues and prs. The page seems fine to me. Just add the logo as per the color scheme of the new logo.

**Comment by RiyaGupta89** [comment]
![logo](https://user-images.githubusercontent.com/72425181/121873460-087f2880-cd24-11eb-935a-ff75bd07a580.png)
Is this the logo you're talking about? If yes, then can you please provide the logo in green color. As black color won't work nice with the color theme.

**Comment by RiyaGupta89** [comment]
Also please label the level too.

**Comment by RiyaGupta89** [comment]
![3](https://user-images.githubusercontent.com/72425181/121875089-ade6cc00-cd25-11eb-838b-764d953cf446.png)
Did you wanted the color scheme like this?

**Comment by RiyaGupta89** [comment]
Shall I request for PR?

**Comment by niloysikdar** [comment]
> ![3](https://user-images.githubusercontent.com/72425181/121875089-ade6cc00-cd25-11eb-838b-764d953cf446.png)
> Did you wanted the color scheme like this?

Yes it is @RiyaGupta89
