### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by Anupam-Panwar** [nilisha-jais/Musicophilia#14]
* Favicon is a great way to customize the website 

![image](https://user-images.githubusercontent.com/65714751/120748727-df3eeb00-c520-11eb-91d4-55fe276efcd5.png)

* I would like to work on this

**Comment by nilisha-jais** [comment]
I'll start assigning issues to all contributors from 10th June when the contribution period starts till then have patience

**Comment by Anupam-Panwar** [comment]
@nilisha-jais Sure

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by RakeshCharpe** [comment]
I like to work on this issue and I'm a participant of LGM Soc21.

**Comment by nisha331** [comment]
Hey mentor and project admin I being a participant at LGMSOC I want to work on this issue it would be great if u could assign this to me.

**Comment by niloysikdar** [comment]
Assigned @nisha331 , go ahead.
