### ISSUE TITLE
Add facebook, instagram and twitter login page

### ISSUE THREAD

**Issue by royalleads15** [nilisha-jais/Musicophilia#147]
## 🚀 Feature

Whenever a user clicks on any of logo of facebook , instagram and twitter he/she get redirected to respective page . Suppose a user clicks on insta logo , after click he must reach insta page of musicophilia .

## Motivation

The motivation for issue come from acessing various music sites .

## Pitch

This feature must be implemented because if anyone wants to connect with musicophilia he/she can do so .

**Comment by royalleads15** [comment]
@niloysikdar  kindly assign this issue to me , so that I can start working upon it.

**Comment by niloysikdar** [comment]
Sure @royalleads15 , go ahead.
