### ISSUE TITLE
Add a Navigation Bar

### ISSUE THREAD

**Issue by vanishasamriddhi** [nilisha-jais/Musicophilia#15]
I would like to work on it, the website would look more appealing

**Comment by nitishapiplani** [comment]
I would like to work on it

**Comment by V-Yeshwanth** [comment]
Hey !! @nilisha-jais i would add responsive nav-bar.
So, I would like to work on this issue.

**Comment by niloysikdar** [comment]
Assigned @V-Yeshwanth , go ahead.

**Comment by nandinimalik16** [comment]
Can you please assign me this issue

**Comment by niloysikdar** [comment]
You have exhausted the given time for an easy issue @V-Yeshwanth . also we don't need it now.
