### ISSUE TITLE
The main menu hamburger not responding 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [nilisha-jais/Musicophilia#16]
![Screenshot_20210605-150103_Chrome](https://user-images.githubusercontent.com/75005433/120887213-2dcab300-c60f-11eb-81c2-e2dc99e5b6a8.jpg)

Hello I am LGM-SOC'21 participant the main-menu hamburger displayed here is not working or not displaying anything Would like to work on it by giving menus to directly go to 
1. Home
2. About Us
3. Contact Us
Can I work on this issue ? @nilisha-jais

**Comment by Vedant-Jayesh-Oza** [comment]
@nilisha-jais ma'am assign this issue to me

**Comment by nitishapiplani** [comment]
I would also like to work on this

**Comment by V-Yeshwanth** [comment]
I Would like to work on it !!!

**Comment by niloysikdar** [comment]
Assigned @V-Yeshwanth , go ahead.

**Comment by niloysikdar** [comment]
Just a small reminder @V-Yeshwanth , you have only 1 day left to complete the issue.

**Comment by harshita2216** [comment]
Unassigned @V-Yeshwanth. Up for grab! 🚀

**Comment by Vedant-Jayesh-Oza** [comment]
Can I work on this issue @harshita2216 @niloysikdar @nilisha-jais ?

**Comment by nitishapiplani** [comment]
May I work on this @nilisha-jais

**Comment by harshita2216** [comment]
Go ahead @nitishapiplani. 🚀

**Comment by nitishapiplani** [comment]
hey hamburger menu is working on my side this issue is wrong i guess

plzz check @nilisha-jais

**Comment by Vedant-Jayesh-Oza** [comment]
Hey @nitishapiplani now its working first it wasn't working someone would have solved it

**Comment by harshita2216** [comment]
@nitishapiplani, thank you for noticing that. We shall now close this issue. Please create other issues or comment on existing ones. 
Thanks. :)

**Comment by nitishapiplani** [comment]
no need @nilisha-jais
