### ISSUE TITLE
Adding an alert box when submit button is clicked without choosing any option in music quiz 

### ISSUE THREAD

**Issue by pallavi-1812** [nilisha-jais/Musicophilia#167]
## 🚀 Feature

I want to add an alert box which will remind user to click on option first when any user clicks submit button in music quiz without clicking on any option.

## Motivation

When submit button is clicked without choosing any option, nothing happens as of now. It is possible for any user to click on submit button by mistake without clicking on any option first and thus he/she might get confused as to why nothing is happening when they click on submit button. Thus it will be better if an alert box pops up reminding user that he/she has forgotten to click on any of the options.

## Pitch

Implementing this feature will enhance the overall user experience. Thus I request you to assign me this issue.

## Add relevant screenshot or video (if any)

(Add here)

**Comment by akshita2903** [comment]
Hey @nilisha-jais  I am a LGM participant.Please assign this issue to me.
/assign

**Comment by nilisha-jais** [comment]
@akshita2903 the issue was opened by @pallavi-1812 so let her complete. You can take up any other issue.

**Comment by akshita2903** [comment]
Okay..
