### ISSUE TITLE
Changing  the favicon as per the current logo.

### ISSUE THREAD

**Issue by nisha331** [nilisha-jais/Musicophilia#169]
## 🚀 Feature
As the logo has changed so favicon if updated would loo much more better.

As a LGMSOC participant I would like to work on it, kindly assign it to me.

**Comment by nisha331** [comment]
@niloysikdar @nilisha-jais kindly check it out.

**Comment by niloysikdar** [comment]
I think you are already working on two issues. As per the rules, you can't take more than two issues. Please complete those first @nisha331

**Comment by nisha331** [comment]
I am working on only issue currently.

**Comment by nisha331** [comment]
I am only working on 1 issue currently

**Comment by niloysikdar** [comment]
Okay, assigned you @nisha331
