### ISSUE TITLE
Display of Social Media Accounts 

### ISSUE THREAD

**Issue by Aiswarika** [nilisha-jais/Musicophilia#17]
I would like to add "follow our social media accounts" at the end of the page. 
@nilisha-jais Please assign me this issue.

**Comment by nandinimalik16** [comment]
I would like to work on this issue as LGM Soc participant

**Comment by Aiswarika** [comment]
@niloysikdar  is this needed? Can you please assign me if needed as I started it first?

**Comment by KhushiRoy** [comment]
I would like to contribute on this issue under LGM SOC 21. Please assign it to me. Thank you.

**Comment by sejalvasan** [comment]
Please assign this issue to me under LGM SOC. Thank you.

**Comment by aditya687** [comment]
I would like to contribute  on this issue and to display some new iconic design for displaying social media accounts.

**Comment by niloysikdar** [comment]
Assigned @Aiswarika , go ahead.

**Comment by Aiswarika** [comment]
@niloysikdar @nilisha-jais  Do review my pull request and let me know if it's fine.

**Comment by aditya687** [comment]
Issue #84

See my pr for footer design  @niloysikdar
