### ISSUE TITLE
Adding More instruments in the band section and enhancing the band page.

### ISSUE THREAD

**Issue by jugeshraghav** [nilisha-jais/Musicophilia#173]
## 🚀 Feature

The band section can have more instruments and user can also see which keys work for which instrument.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Now user doesn't know that the band can also be played with he keyboard keys. We can add some feature which enables the user to know about which key of keyboard corresponds to which instrument. 
Also we can add some more instruments in the drum.

## Add relevant screenshot or video (if any)

(Add here)

**Comment by jugeshraghav** [comment]
please assign this issue to me @niloysikdar @nilisha-jais

**Comment by niloysikdar** [comment]
Assigned @jugeshraghav , go ahead
