### ISSUE TITLE
Go back to top button 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [nilisha-jais/Musicophilia#18]
The footer of the website doesn't have a go "back to top of the page button" so I want to make a button at the footer of the page just like in the given image, which lets user to go directly to the top of the website instead of scrolling the page, can I do that ? 

I am a LGM-SOC'21 Participant please ma'am assign this issue to me I would love to work on it 

![Screenshot_20210605-155833_Chrome](https://user-images.githubusercontent.com/75005433/120888625-f4964100-c616-11eb-851a-3639f39854ad.jpg)

**Comment by nilisha-jais** [comment]
Assigning you @Vedant-Jayesh-Oza

**Comment by Vedant-Jayesh-Oza** [comment]
Okay will do this @nilisha-jais 👍👍
