### ISSUE TITLE
Improve social-media icons

### ISSUE THREAD

**Issue by akshita2903** [nilisha-jais/Musicophilia#187]
## 🚀 Feature

I want to add some glowing and hover effect on social media icons

## Pitch
The motivation comes from various music or any other sites where when user clicks on social media icons it shows some glow/hover effect
The social media icons looks very simple when you click or select then,so I wanna improve it

## Add relevant screenshot or video (if any)

(Add here

**Comment by akshita2903** [comment]
@niloysikdar  please assign this issue to me

**Comment by niloysikdar** [comment]
Assigned @akshita2903
