### ISSUE TITLE
Improvisation of "Contact Us" section 

### ISSUE THREAD

**Issue by surbhi594** [nilisha-jais/Musicophilia#188]

**Comment by surbhi594** [comment]
I want to work on this issue. Please /assign it to me as I'm an LGMSOC'21 participant.

**Comment by niloysikdar** [comment]
@surbhi594 please elaborate more on the issue.

**Comment by surbhi594** [comment]
@niloysikdar I want to enhance the UI of the "contact us" section.

**Comment by niloysikdar** [comment]
There are already some issues opened related to the improvement of Contact Us page.
