### ISSUE TITLE
extra back link is given in bottom left side of the band page.

### ISSUE THREAD

**Issue by starrohan999** [nilisha-jais/Musicophilia#192]
## 🐛 Bug Report

There is an extra link is given on the bottom left-hand side of the band page.
we can simply remove it.

## Add relevant screenshot or video (if any)

![2021-06-13_LI](https://user-images.githubusercontent.com/71714344/121788037-b20ccf80-cbe7-11eb-94d8-af084569b076.jpg)

**Comment by starrohan999** [comment]
@niloysikdar if it going to add more value in website please assign it to me.

**Comment by niloysikdar** [comment]
Assigned @starrohan999

**Comment by starrohan999** [comment]
close this issue
