### ISSUE TITLE
Home page not responsive

### ISSUE THREAD

**Issue by aum-singhal** [nilisha-jais/Musicophilia#194]
## 🐛 Bug Report

Home page is not responsive for mobile.

I will be glad to contribute in this issue.
I am a LGM-SOC participant.

Thanks 😊

## Add relevant screenshot or video (if any)

![Screenshot_2021-06-13-07-40-35-07.jpg](https://user-images.githubusercontent.com/69421286/121793328-a804c400-cc1b-11eb-8c57-17b3bb62df42.jpg)

**Comment by niloysikdar** [comment]
Go ahead @aum-singhal
