### ISSUE TITLE
Revamp the home page

### ISSUE THREAD

**Issue by nilisha-jais** [nilisha-jais/Musicophilia#2]
Modify index.html file. Change the navbar, footer and UI of the page

**Comment by kumarishalini6** [comment]
@nilisha-jais  I want to work on this issue i am participant of LGM-SOC'21 .

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by jugeshraghav** [comment]
Please assign this issue to me. I want to work on this issue and make the website's look and feel better. I am a participant of LGM-SoC

**Comment by kumarishalini6** [comment]
@jugeshraghav , @Jagannath8  issues assign on the basis of first come first serve.

**Comment by Nikhita28** [comment]
I would like to work on this issue under lgmsoc 2021

**Comment by kumarishalini6** [comment]
@nilisha-jais  please assign this issue to me

**Comment by niloysikdar** [comment]
Assigned @Nikhita28 , you can start working on the issue.

**Comment by kumarishalini6** [comment]
@niloysikdar but the issue assigned on the basis of first come first serve and I am the first one

**Comment by niloysikdar** [comment]
`And for the issues which have already opened before the contribution period, we have assigned those to the users who have commented first after the starting of the contribution period.`

-- Check Slack channel for more clarity. @kumarishalini6
