### ISSUE TITLE
Enhance the band page

### ISSUE THREAD

**Issue by coding-geek21** [nilisha-jais/Musicophilia#20]
I would like to work on this issue under LGM-SOC , Can you please assign me @nilisha-jais 

We can make the band page more attractive by adding high quality images and illustrations

**Comment by coding-geek21** [comment]
Can you please assign me? i would like to work on it @niloysikdar

**Comment by nilisha-jais** [comment]
Hey what would kind of images do you want to add...please elaborate

**Comment by coding-geek21** [comment]
Vector illustrations Would look attractive

**Comment by nilisha-jais** [comment]
Assigned @coding-geek21

**Comment by coding-geek21** [comment]
> Assigned @coding-geek21

Thank you :)

**Comment by niloysikdar** [comment]
Small reminder @coding-geek21 , just one more day left to complete this task.

**Comment by harshita2216** [comment]
Unassigned @coding-geek21.

**Comment by joydeepnandi** [comment]
Can I work on this? @harshita2216

**Comment by Srijan1878** [comment]
Can you assign this to me? @harshita2216
