### ISSUE TITLE
Adding Buttons having dance categories to fetch and show related videos

### ISSUE THREAD

**Issue by ShwetKhatri2001** [nilisha-jais/Musicophilia#200]
## 🚀 Feature

We can add buttons having dance categories at top  

## Motivation

User can find videos based on selected category

## Pitch

Currently we are fetching videos for world's best dances , that query parameter can be changed dynamically and we can get videos related to that query parameter onclick to a particular category button

@niloysikdar Assign this during LGM-SOC contribution period.

**Comment by niloysikdar** [comment]
Assigned @ShwetKhatri2001
