### ISSUE TITLE
Upgrading the footer section

### ISSUE THREAD

**Issue by ArshWalker** [nilisha-jais/Musicophilia#204]
## 🚀 Feature

(A clear and concise description of what the feature is.)
1. Making the year dynamic in the footer.
2. Some CSS modifications.

@nilisha-jais please assign me under LGMSOC21

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue. Do assign me if possible. Thank You!

**Comment by niloysikdar** [comment]
Check #181 @ArshWalker
