### ISSUE TITLE
Change the position of badges

### ISSUE THREAD

**Issue by Umesh-01** [nilisha-jais/Musicophilia#209]
## 📚 Documentation
I think these badges are not looking good enough. I want to align them to the center.

## Add relevant screenshot or video (if any)
![image](https://user-images.githubusercontent.com/83420185/121816429-2784a880-cc99-11eb-8859-ccb0db5132bb.png)

**Comment by Umesh-01** [comment]
@nilisha-jais mam should I work on this under LGMSOC??

**Comment by Umesh-01** [comment]
@nilisha-jais mam should I make these changes??

**Comment by nilisha-jais** [comment]
Go ahead @Umesh-01

**Comment by Umesh-01** [comment]
@nilisha-jais mam there are some images and gifs in README.md file, should I add links to them because without them these are of no use...

For this should I raise a new ISSSUE??

Example-
![image](https://user-images.githubusercontent.com/83420185/121847934-f6db5800-cd06-11eb-8f91-ec8727b1fb05.png)

![image](https://user-images.githubusercontent.com/83420185/121847963-fe9afc80-cd06-11eb-8b28-44ffa6ed0259.png)

**Comment by niloysikdar** [comment]
Please elaborate a little more @Umesh-01

**Comment by Umesh-01** [comment]
Hello @niloysikdar sir,
are u a maintainer??

**Comment by Umesh-01** [comment]
> Please elaborate a little more @Umesh-01

I mean if any user by mistake or intentionally clicks on these gifs then they must be redirected to the files of Code of Conduct or License without this these gifs or images are of no use.

Now they are like this after clicking on them, means this is of no use...

![image](https://user-images.githubusercontent.com/83420185/121850177-fe503080-cd09-11eb-89b0-d8788f1baa1d.png)

**Comment by niloysikdar** [comment]
Yeah sure @Umesh-01 , please add the relevant links.

**Comment by Umesh-01** [comment]
so what should I do to make these changes??
a new issue??

**Comment by niloysikdar** [comment]
No just push the new changes in the same pr which you have opened.

**Comment by niloysikdar** [comment]
Just need to add two links @Umesh-01

**Comment by Umesh-01** [comment]
ok @niloysikdar sir 👍 , thanks 🙂

**Comment by Umesh-01** [comment]
@niloysikdar sir done, check it and merge if everything is fine 😄
