### ISSUE TITLE
Underline in the back button of the quiz game 

### ISSUE THREAD

**Issue by Amit-45** [nilisha-jais/Musicophilia#216]
![Screenshot (179)](https://user-images.githubusercontent.com/77204104/121842007-27b68f80-ccfd-11eb-804e-d10e68334f78.png)

There is an underline in the back button(in the Quiz Game Page) as it is a button created by Hyperlink . 
The underline under the text of the Back Button can be removed .

If you think that needs to be changed  please assign this issue under the LGMSOC'21

**Comment by Sumit11081996** [comment]
@Amit-45 can you assign me this issue

**Comment by niloysikdar** [comment]
Assigned @Amit-45
