### ISSUE TITLE
theme changer

### ISSUE THREAD

**Issue by bharth-stack** [nilisha-jais/Musicophilia#219]
## 🚀 Feature

want to add a button to change theme to light , light to dark 

## Motivation

every music players have this function
## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by jugeshraghav** [comment]
Can I work on this issue.

**Comment by niloysikdar** [comment]
Assigned @bharth-stack . 
Definitely, you can @jugeshraghav if @bharth-stack fails to complete the task within the given time. Till then explore the other issues if possible.
