### ISSUE TITLE
hover animation in the music play cards

### ISSUE THREAD

**Issue by manognyaa** [nilisha-jais/Musicophilia#22]
hello mam,
I would like to add hover animation to this website. As you can see the music cards are not filled with colors. 
I will create a hover animation like whenever the cursor hovers on the music play cards, the music card will move little bit ups and down. It will really look amazing.
please assign this to me mam @nilisha-jais  :)

**Comment by KhushiRoy** [comment]
I would like to add hover animation using CSS. Please assign this to me under LGM SOC 21

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?
