### ISSUE TITLE
Add Flute Music Section.

### ISSUE THREAD

**Issue by codebuzzer01** [nilisha-jais/Musicophilia#224]
## 🚀 Feature

Add a complete another section of flute chords.

## Motivation

Flute music is one of the most peaceful and soothing music.

## Pitch

Flute music will definitely be worth a section. It will add variety to this website and users will undoubtedly enjoy it more.

**Comment by codebuzzer01** [comment]
@nilisha-jais If u find it suitable, then assign it to me under LGM-SOC'21

**Comment by niloysikdar** [comment]
Assigned @codebuzzer01 , go ahead.
