### ISSUE TITLE
Memory game changes

### ISSUE THREAD

**Issue by Khushi-agarwal** [nilisha-jais/Musicophilia#225]
## 🚀 Feature

This page doesn't looks good and also the elements are not aligned properly
![image](https://user-images.githubusercontent.com/76625662/121853159-2e99ce00-cd0e-11eb-9b77-e94363d3152e.png)
I would like to work on this.

**Comment by niloysikdar** [comment]
Assigned @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
@niloysikdar can I add a gif to the background?

**Comment by niloysikdar** [comment]
Sure @Khushi-agarwal
