### ISSUE TITLE
Resize the music box

### ISSUE THREAD

**Issue by ankh77sb** [nilisha-jais/Musicophilia#228]
## 🐛 Bug Report

The music box page seems pretty cool and well done. But it seems to require scrolling on my viewport. So i would like to resize it to avoid the scrolling in that page

## Add relevant screenshot or video (if any)

(Add here)
![musicophilia](https://user-images.githubusercontent.com/59738300/121856020-a4ebff80-cd11-11eb-8ecd-1e2f274d29fc.JPG)

**Comment by ankh77sb** [comment]
Please kindly look into it assign it to me 
or
Let me know if i can assign it to myself

**Comment by niloysikdar** [comment]
Sure @ankh77sb , assigned you the issue. Kindly align the back button to the top left corner also.

**Comment by ankh77sb** [comment]
I have made a pull request. Please suggest changes if any 
Need some more time to work on view port sizes below 425 .. the cause of extra space on bottom is not yet found

**Comment by niloysikdar** [comment]
Sure @ankh77sb
