### ISSUE TITLE
CURSOR ANIMATION

### ISSUE THREAD

**Issue by manognyaa** [nilisha-jais/Musicophilia#23]
hello mam,
what if the cursor changes from normal cursor to a disco-light cursor ? sounds good right mam :) 
Adding to it,  the cursor will stop once we don't move the cursor.  the theme is music and I thought why not something new this time.
I would like to work on this issue
please assign this to me mam @nilisha-jais  :)

**Comment by nilisha-jais** [comment]
Go ahead @manognyaa your feature sounds amazing!!

**Comment by manognyaa** [comment]
> Go ahead @manognyaa your feature sounds amazing!!

thank you mam
@nilisha-jais
