### ISSUE TITLE
Change Copyright year using JS

### ISSUE THREAD

**Issue by Shaishav0507** [nilisha-jais/Musicophilia#233]
## 🚀 Feature

Hey @nilisha-jais 
I would like to change the copyright year and add using the Js, where you need not update everytime.
It will automatically update itself.
Please assign it to me.
Thanks

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by niloysikdar** [comment]
Not needed @Shaishav0507
