### ISSUE TITLE
 open url in new tab on button click

### ISSUE THREAD

**Issue by vimalprogrammer** [nilisha-jais/Musicophilia#244]
## 🐛 Bug Report

A clear and concise way is to open the URL is to the new tab, not the same tap.

<h2>WRONG </h2>

![WhatsApp Image 2021-06-14 at 6 19 41 PM (1)](https://user-images.githubusercontent.com/76787061/121894867-43418a80-cd3d-11eb-8dd5-6fb7e1ddb3b8.jpeg)

<h2>Onclick open in new tap CORRECT WAY</h2>

![WhatsApp Image 2021-06-14 at 6 19 41 PM](https://user-images.githubusercontent.com/76787061/121894873-450b4e00-cd3d-11eb-94df-b21ed48ecd21.jpeg)

I would like to work on this issue under LGMSOC, please assign me!

**Comment by vishal-codes** [comment]
I would like to work on this bug. I have experience with the mentioned feature as I have implemented the required feature in my portfolio website.  Please assign this issue to me under LGM-SoC.

**Comment by niloysikdar** [comment]
Is it necessary @nilisha-jais ?

**Comment by vimalprogrammer** [comment]
> Is it necessary @nilisha-jais ?

I guess opening in new tab on clicking, might be a convenient way.

**Comment by nilisha-jais** [comment]
we have an option of back button I guess we don't need it

**Comment by vimalprogrammer** [comment]
> we have an option of back button I guess we don't need it

@nilisha-jais @niloysikdar  yeah! My bad, I now only saw the updation of the back button! Like to contribute in different ways😊.
