### ISSUE TITLE
Back button in music quiz section

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [nilisha-jais/Musicophilia#247]
## 🐛 Bug Report

The back button is music quiz section has an underline but on the other pages it doesn't have it. I would like to remove that line as it doesn't seem good and is not like other buttons too

## Add relevant screenshot or video (if any)

![image](https://user-images.githubusercontent.com/54837213/121908674-d7feb500-cd4a-11eb-8d8f-c7013efc5fd3.png)

**Comment by nilisha-jais** [comment]
Check #216
