### ISSUE TITLE
Add seekbar in Music box player

### ISSUE THREAD

**Issue by Aniket979Kanodia** [nilisha-jais/Musicophilia#25]
Seekbar will helpful in navigating through the music and give user friendly experience.

**Comment by Aniket979Kanodia** [comment]
@nilisha-jais  I would like to work on this issue.
Please assign me when coding period start.

**Comment by nilisha-jais** [comment]
Assigning you @Aniket979Kanodia

**Comment by niloysikdar** [comment]
Small reminder @Aniket979Kanodia , you have only one more day left to complete this task.

**Comment by Aniket979Kanodia** [comment]
@niloysikdar 
I am done with HTML and CSS part of project.
Also JAVA SCRIPT part is almost done. 
But there are some issues left and I am working on them. It might take three days. It would be helpful if you could provide me some more time.

**Comment by niloysikdar** [comment]
Sure @Aniket979Kanodia , thanks for the information about your progress.
