### ISSUE TITLE
Adding a metronome 

### ISSUE THREAD

**Issue by Adarsh88** [nilisha-jais/Musicophilia#250]
## 🚀 Feature

Adding a metronome to Musicophilia

## Pitch

Everyone needs a metronome for practicing their music whether it may be guitar or some other instrument. For example we use a metronome for practicing chord shifts in guitar. So I thought of implementing it in this website.

I'm a participant of LGM-SOC'21. So please add the necessary tags!

**Comment by niloysikdar** [comment]
Assigned @Adarsh88
