### ISSUE TITLE
Question number not shown in Music Quiz

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [nilisha-jais/Musicophilia#253]
## 🐛 Bug Report

In the Music Quiz while attempting the questions, question number is not shown. This creates confusion for the user

## Add relevant screenshot or video (if any)
![image](https://user-images.githubusercontent.com/54837213/121917186-80fcde00-cd52-11eb-9654-ff2629c68977.png)

**Comment by Sukhseerat-Kaur** [comment]
@niloysikdar Kindly assign me this under LGM-SoC'21

**Comment by niloysikdar** [comment]
Assigned @Sukhseerat-Kaur
