### ISSUE TITLE
flip the card and give some facts

### ISSUE THREAD

**Issue by royalleads15** [nilisha-jais/Musicophilia#267]
## 🚀 Feature

As the user hovers his mouse on any card the card flip and give some genuine info about that . For ex whenever a users hovers his mouse on piano , the piano card flips and gives some info like when piano was first played or how to play piano etc .

## Motivation

The motivation comes from more and more analyzing your website .

## Pitch

By adding this feature, one who didn't know about that respective instrument can also use or play it .

**Comment by gargi111** [comment]
I want to work on this task .Pls assign me for this work.

**Comment by niloysikdar** [comment]
Assigned @royalleads15

**Comment by jatinjain001** [comment]
I would like to work on it 
If it is available let me know

**Comment by jatinjain001** [comment]
I would like to work on it 
If it is available let me know
