### ISSUE TITLE
Update readme file to help beginners contribute to open source 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [nilisha-jais/Musicophilia#27]
Hello, I am a LGM-SOC'21 Participant 
I am a Newbie coder And a beginner to open source contributions,  I learnt open source contributions recently so I would like to update this Readme file where I will give some detailed steps to contribute to this project so that the Readme file can be more beginner friendly.
Assign this issue to me.

**Comment by RakeshCharpe** [comment]
I would like to update Readme file so it can help beginners to how to contribute in projects and make a pull request .Please assign to me under LCM Soc21

**Comment by Vedant-Jayesh-Oza** [comment]
@RakeshCharpe actually I have already raised this issue and asked to assign it to me 😅😅

**Comment by Vedant-Jayesh-Oza** [comment]
@RakeshCharpe actually I have raised this issue so I have asked PA and mentors to assign it to me 😅😅

**Comment by RakeshCharpe** [comment]
Ok no problem i thought it is not assigned to anyone .

**Comment by niloysikdar** [comment]
Assigned @Vedant-Jayesh-Oza , go ahead.

**Comment by Vedant-Jayesh-Oza** [comment]
Okay will start working on this issue 👍
