### ISSUE TITLE
Tabla icon is missing

### ISSUE THREAD

**Issue by ambivert-sam** [nilisha-jais/Musicophilia#275]
## 🚀 Feature

On the home page, there is the missing icon of tabla I want to add that icon
I would like to contribute and work on this issue as a participant of LGM SOC'21 will you please assign it to me

## Add relevant screenshot or video (if any)
![Screenshot (193)](https://user-images.githubusercontent.com/74984661/122022594-5d827380-cde4-11eb-93f8-2111c22b4ab6.png)

**Comment by niloysikdar** [comment]
That was fixed @ambivert-sam
