### ISSUE TITLE
Making Navbar-Sticky and adding top-button

### ISSUE THREAD

**Issue by SamikshaSankar** [nilisha-jais/Musicophilia#28]
Navbar sticky- The navbar will stick to the top when you reach its scroll position
Top-button - button that becomes visible when the user starts to scroll the page

 I work on this issue under LGM-SOC'21 participant..please assigned me

**Comment by nisha331** [comment]
hey Mentor and project admin as the coding period starts, I as a participant of LGMSOC would like to work on this issue . It would be great if you could assign it to me

**Comment by niloysikdar** [comment]
Assigned @nisha331 , go ahead.

**Comment by SamikshaSankar** [comment]
@niloysikdar I think I am comment on this first Right...Others mentors also follow the same rule.. (this happened with me also the mentors said ur 2 so I am not able to assigned this issue to u)

**Comment by niloysikdar** [comment]
`And for the issues which are already opened before the contribution period, we have assigned those to the users who have commented first after the starting of the contribution period. `

-- Check Slack Channel for more info.

**Comment by niloysikdar** [comment]
@SamikshaSankar

**Comment by SamikshaSankar** [comment]
![IMG_20210610_181054](https://user-images.githubusercontent.com/52104082/121526699-41af5400-ca17-11eb-8227-904e06b28146.jpg)

.. 8 Jun
