### ISSUE TITLE
(Bug) Fixing Instrument gif not loading in About Section

### ISSUE THREAD

**Issue by ArshWalker** [nilisha-jais/Musicophilia#288]
## 🐛 Bug Report

In the about section, the gif for the instrument is not loaded/showing.

I will fix that bug.
## Add relevant screenshot or video (if any)
![image](https://user-images.githubusercontent.com/54627391/122089532-7ad73200-ce24-11eb-98eb-0277c951521a.png)

@nilisha-jais Please Assign me under LGMSOC21.

**Comment by niloysikdar** [comment]
Assigned @ArshWalker
