### ISSUE TITLE
Theme, UI change Revamp contact page

### ISSUE THREAD

**Issue by RahulBansal0502** [nilisha-jais/Musicophilia#291]
This website is awesome but I think the color combination of green is not so good on hovering somewhere there is black color or gray everywhere is different. I want to use the gradient of green instead of pure green color.

2. On the home page on hovering cards are colliding with each other. I want to align them.
3.  Revam Contact us page.

I wanted to work on these issues @nilisha-jais Assign it to me. Thanks

**Comment by akitiashritha** [comment]
/assign
I would like to work on the revamping the contact us page 
please assign it to me @nilisha-jais

**Comment by harshita2216** [comment]
@akitiashritha, I request you to pause your work for now as the mentors would be discussing who it should be assigned to. Thanks.

**Comment by harshita2216** [comment]
@RahulBansal0502, We have decided to assign this to you. Please go ahead.

**Comment by RahulBansal0502** [comment]
Ok Thanks. Can you please label it as LGMSOC21

**Comment by RahulBansal0502** [comment]
@nilisha-jais actually I have raised 3 issues under this and 2 are remaining so can u open this again or I will raise it again

**Comment by nilisha-jais** [comment]
Okay
