### ISSUE TITLE
Automatic Upgradation of Copyright Year

### ISSUE THREAD

**Issue by ghost** [nilisha-jais/Musicophilia#296]
## 🚀 Feature

The Year in the footer will update itself automatically every time by adding only a line of code 

## Motivation

In the current project every year we need to update the copyright year manually which can be solved

## Additional context

Please assign this project to me. I am a participant of LGMSOC21

**Comment by niloysikdar** [comment]
What is the value of this issue ? @Kritika-2000

**Comment by ghost** [comment]
@niloysikdar I will add a script using which we do not need to update the copyright every year manually . It will automatically update itself every time and doesn't need any manual upgradation .

**Comment by niloysikdar** [comment]
Okay fine go ahead @Kritika-2000

**Comment by ghost** [comment]
@niloysikdar thank you ✌️
