### ISSUE TITLE
Add a contact us page

### ISSUE THREAD

**Issue by nilisha-jais** [nilisha-jais/Musicophilia#3]

**Comment by kumarishalini6** [comment]
@nilisha-jais can I work on this issue under LGM-SOC'21 participant

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by BeginnerCoder21** [comment]
@nilisha-jais I can work on this issue, I am a LGM-SOC'21 participant.

**Comment by Aiswarika** [comment]
Can I work on this issue as an LGM SOC participant? @nilisha-jais

**Comment by Vedant-Jayesh-Oza** [comment]
Can I work on this issue ? I am a LGM-SOC'21 participant 
@nilisha-jais

**Comment by Anuradha0501** [comment]
Can I work on this issue as an LGM-SOC'21 participant
@nilisha-jais

**Comment by akshikamudgal** [comment]
can I work on it 
/assign

**Comment by akitiashritha** [comment]
Can I work on this issue ? 
@nilisha-jais

**Comment by niloysikdar** [comment]
Assigned, go ahead @akshikamudgal

**Comment by akshikamudgal** [comment]
you have merged my code still it is not showing me as a contributor. why?

**Comment by niloysikdar** [comment]
@akshikamudgal , maybe your pr has been reverted, idn, I haven't reverted any pr as of now. @nilisha-jais  can you help in this issue ?

**Comment by akshikamudgal** [comment]
Code is merged check it out why not added as an contributor @nilisha-jais

**Comment by nilisha-jais** [comment]
We are looking into the issue
Did you commit via a different git mail than what is in your GitHub profile??

**Comment by akshikamudgal** [comment]
> We are looking into the issue
> Did you commit via a different git mail than what is in your GitHub profile??

No

**Comment by niloysikdar** [comment]
Hey @akshikamudgal , we have found the issue. Please have a look at the screenshot and [this doc](https://docs.github.com/en/github/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user). @nilisha-jais was correct.

<img src="https://user-images.githubusercontent.com/58071992/122542308-2dd3a580-d048-11eb-8dca-75e23be5366e.PNG" width="1000">

**Comment by akshikamudgal** [comment]
Check this once and guide me what to do.
![image](https://user-images.githubusercontent.com/66902249/122544416-6d02f600-d04a-11eb-8f13-3b4a5c2b395f.png)

**Comment by nilisha-jais** [comment]
You please set up your git bash with the same mail id as in your github account

**Comment by akshikamudgal** [comment]
> You please set up your git bash with the same mail id as in your github account

I have checked that it is same for both.

**Comment by akshikamudgal** [comment]
Any updates ???? @nilisha-jais

**Comment by nilisha-jais** [comment]
I cannot help you in this case as there was an issue from your end
Check [this](https://github.com/nilisha-jais/Musicophilia/pull/389)  she too did the same but we were able to figure out

**Comment by nilisha-jais** [comment]
All we can do is when you make your next pull request we can assign it a higher level so that we can make up the loss
