### ISSUE TITLE
Add Footer tag & place social media icons

### ISSUE THREAD

**Issue by ss-sahoo** [nilisha-jais/Musicophilia#30]

**Comment by ss-sahoo** [comment]
@nilisha-jais please assign me........I would like to do some changes

**Comment by Sanika2103** [comment]
@nilisha-jais I would like to work on this issue. Will you assign it to me?

**Comment by SanskritiKushik5** [comment]
Please assign me this issue under LGMSOC.

**Comment by Sanika2103** [comment]
I have participated in LGM-SOC

**Comment by LegendSumeet** [comment]
Can we work as team?

**Comment by niloysikdar** [comment]
Check #17
