### ISSUE TITLE
ADD cursor : pointer property in every button on page of the website.

### ISSUE THREAD

**Issue by starrohan999** [nilisha-jais/Musicophilia#302]
## 🚀 Feature

On the whole website, there are many buttons but when we hover on them the cursor did not change to Pointer.
So I would like to add on every page.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by saloni32** [comment]
I would like to work on this issue if available.
