### ISSUE TITLE
Adding Footer in About Section

### ISSUE THREAD

**Issue by ArshWalker** [nilisha-jais/Musicophilia#312]
## 🚀 Feature

I will add a footer section in the about section.

@nilisha-jais @niloysikdar Please assign me under LGMSOC21

**Comment by Sumit11081996** [comment]
@nilisha-jais  please assign me this issue

**Comment by ArshWalker** [comment]
@Sumit11081996 it's my issue brother.

**Comment by ArshWalker** [comment]
@nilisha-jais please assign me under LGMSOC21

**Comment by Aditi-Singh16** [comment]
@ArshWalker actually I have opened this issue 2 days before and even made the pull request today, so I think you can close this issue :).

**Comment by ArshWalker** [comment]
@Aditi-Singh16 ok, np!
