### ISSUE TITLE
footer icons

### ISSUE THREAD

**Issue by rishika789** [nilisha-jais/Musicophilia#318]
footer icons colour is not much distinguised by the background of footer . I would like to change that.

![image](https://user-images.githubusercontent.com/78673968/122260987-85abc880-cef1-11eb-83b7-cdaa5e13a7db.png)

**Comment by rishika789** [comment]
@nilisha-jais 
@niloysikdar 
please assign me this

**Comment by niloysikdar** [comment]
Assigned @rishika789
