### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [nilisha-jais/Musicophilia#320]
Add LGM-SOC'21 score card in readme.md

**Comment by niloysikdar** [comment]
Can you please tell more about this issue ?

**Comment by ishitakapoor26** [comment]
> Can you please tell more about this issue ?

@niloysikdar I want to add this
![score card](https://user-images.githubusercontent.com/78542333/122349754-2c33b000-cf6a-11eb-9fe2-6fda87af15ca.PNG)

**Comment by niloysikdar** [comment]
Should we add this @nilisha-jais  ?

**Comment by ishitakapoor26** [comment]
@niloysikdar I can add this in text format too
![labels](https://user-images.githubusercontent.com/78542333/122356162-280a9100-cf70-11eb-931d-410a7b44dc05.PNG)

**Comment by nilisha-jais** [comment]
@ishitakapoor26 there's no point to add this....Not needed!
