### ISSUE TITLE
Improvising the Quiz game 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [nilisha-jais/Musicophilia#33]
Hello I am LGM-SOC'21 participant, 
I would like to add some more questions in the music quiz section and also I will try implementing a timer in the music Quiz section 
Please assign This issue to me @nilisha-jais ma'am

**Comment by nilisha-jais** [comment]
Go ahead @Vedant-Jayesh-Oza . Assigning you!

**Comment by niloysikdar** [comment]
Small reminder @Vedant-Jayesh-Oza , you have one more day left to complete this task. We have already implemented API for the questions, you can add a timer.

**Comment by Vedant-Jayesh-Oza** [comment]
Hello @niloysikdar sir I have my exams going on, I had a word with PA and I also dm'd you about my exams on slack please consider 😅

**Comment by niloysikdar** [comment]
No issues @Vedant-Jayesh-Oza , thanks for letting us know about the problem.
