### ISSUE TITLE
About section's Card Images are not aligned properly 

### ISSUE THREAD

**Issue by ashuydv** [nilisha-jais/Musicophilia#335]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/67309431/122383925-dcb0ac80-cf88-11eb-8998-f1c02baf5763.png)

In this picture, the cards images are not of proper width, 

What can I do, is to make it of its full width, and make it look awesome, Plz assign me this issue under lgm soc 

Thank You,

**Comment by nilisha-jais** [comment]
Go ahead @ashuydv
