### ISSUE TITLE
Make UI more engaging

### ISSUE THREAD

**Issue by ashuydv** [nilisha-jais/Musicophilia#337]
## 🚀 Feature
We can make UI more engaging by adding gradient colors and by keeping the colors same through out the website, like what we can do is,

- make navbar either dark or transparent, 
-  Adding transitions in navbar .i.e. the underline one ,
- modify the contact form and make it more user friendly
- We can make the loader, more amazing and engaging by making it bit smalller and make it of full length

Here's the link : https://dribbble.com/shots/15236974-Filebox-UI-Kit?utm_source=Clipboard_Shot&utm_campaign=brightscout&utm_content=Filebox%20UI%20Kit&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=brightscout&utm_content=Filebox%20UI%20Kit&utm_medium=Social_Share

**Comment by niloysikdar** [comment]
Assigned @ashuydv
