### ISSUE TITLE
Add navbar in About and Login page

### ISSUE THREAD

**Issue by Shaishav0507** [nilisha-jais/Musicophilia#338]
## 🚀 Feature

Hey @nilisha-jais @niloysikdar 
I would like to add navbar in about and login page
Please assign it to me.
Thanks

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by Aditi-Singh16** [comment]
hello @Shaishav0507,

Actually, I have opened the issue 2 days before and even made the pull request today
So this issue has been resolved :)

**Comment by Shaishav0507** [comment]
@Aditi-Singh16 It's only done in about.
I'll do in login.

**Comment by nilisha-jais** [comment]
Go ahead! About page already has one....You just need to add in the login page
