### ISSUE TITLE
Make a register user page

### ISSUE THREAD

**Issue by Aditi-Singh16** [nilisha-jais/Musicophilia#340]
## 🚀 Feature

Register user page will take all the necessary details from users and create their account after required validations.

## Motivation

This registration page will help us keep track of users, who are enjoying the musicophilia website, and also help us save the user's activity.

## Pitch
With the help of this:
1. we can know the number of users enjoying the website
2. help us track the recent activity of the user
3. we can keep registered users updated with our latest features
4. This will help better engagement with the user.

Implementation:
I just need to add a form with the required input fields and do the verification.

## Add relevant screenshot or video (if any)

(Add here)

**Comment by Aditi-Singh16** [comment]
@nilisha-jais should I proceed to work on this feature?.

**Comment by nilisha-jais** [comment]
There's already a login page

**Comment by Aditi-Singh16** [comment]
okay i will close it
