### ISSUE TITLE
add password validation in login page

### ISSUE THREAD

**Issue by Aditi-Singh16** [nilisha-jais/Musicophilia#341]
## 🐛 Bug Report

We can see that if the password field is empty the button is still being clicked, which should not happen
also there is no validation for passwords like 6 characters only, at least one special character, etc.
I would like to work on this issue.

**Comment by Srit20** [comment]
can i work on this issue. I'm a participant of LGM-SOC21

**Comment by niloysikdar** [comment]
Go ahead @Srit20

**Comment by Srit20** [comment]
my work is going on

**Comment by harshita2216** [comment]
> my work is going on

Great! Keep us updated. Thanks. @Srit20

**Comment by sanketcharanpahadi** [comment]
can I work on this issue @niloysikdar ?

**Comment by harshita2216** [comment]
@sanketcharanpahadi, We would be assigning in case @Srit20 is not working on this issue anymore. 
@Srit20, please give us some updates?

**Comment by Srit20** [comment]
i have tried a lot but i can't solve please assign to other .

**Comment by harshita2216** [comment]
Okay @Srit20, no issues at all. Thanks for informing. 
@sanketcharanpahadi, you can now work on this issue.
