### ISSUE TITLE
Increase site performance

### ISSUE THREAD

**Issue by WebShivam** [nilisha-jais/Musicophilia#346]
## 🐛 Bug Report!
The site takes a lot time while loading which will lead to non-engaging audience in future and nobody wants that, hence it needs to be looked after and loading speed needs to increased

## Add relevant screenshot or video (if any)
GT Metrix which is a popular web performance site Tester recommends loading time of contents to <=1.3 seconds for good user Experience but this site took ~3.4s to load, Hence it needs to be looked upon. Here is the Image 👇 

![Screenshot_44](https://user-images.githubusercontent.com/64413107/122428256-63788000-cfaf-11eb-8c80-2573b4be737e.jpg)

**Comment by nilisha-jais** [comment]
Go ahead @WebShivam .Fix this!
