### ISSUE TITLE
navbar on hovering

### ISSUE THREAD

**Issue by rishika789** [nilisha-jais/Musicophilia#353]
the right side buttons on navbar on hovering changes to grey not maching theme of website.
I would like to change the effect.

![Screenshot (913)](https://user-images.githubusercontent.com/78673968/122450574-cb859100-cfc4-11eb-936d-187de5b312d8.png)

**Comment by rishika789** [comment]
@niloysikdar 
@nilisha-jais

**Comment by niloysikdar** [comment]
We have already solved the hovering issue, but yeah you can enhance the active state. @rishika789

**Comment by rishika789** [comment]
> We have already solved the hovering issue, but yeah you can enhance the active state. @rishika789

LIKE WE SHOULD KNOW WHICH PAGE ARE WE VIEWING?

**Comment by niloysikdar** [comment]
Yes, you can see [here ](https://deploy-preview-350--musicophilia.netlify.app/)

**Comment by rishika789** [comment]
OK LIKE ACTIVE STATE COLOUR SCHEME WILL BE CHANGED

**Comment by rishika789** [comment]
ONCE PLEASE HAVE A  LOOK  ON ISSUE #354  ALSO

**Comment by rishika789** [comment]
> Yes, you can see [here ](https://deploy-preview-350--musicophilia.netlify.app/)

BUT WHEN I OPEN THE WEBSITE IT IS STILL HAVING THE OLD LOOK LIKE NAVBAR CONTAINS BUTTONS FOR EACH.

musicophilia.netlify.app/

**Comment by niloysikdar** [comment]
Cz we haven't merged the pr yet @rishika789 , but we will merge soon

**Comment by rishika789** [comment]
OKK SO AFTER MERGING ONLY I CAN DO CHANGES RIGHT ?

**Comment by rishika789** [comment]
> OKK SO AFTER MERGING ONLY I CAN DO CHANGES RIGHT ?

BECUSE IN THAT CSS PR THERE MUST BE CHANGES, AFTER MERGING PLEASE LET ME KNOW.

**Comment by niloysikdar** [comment]
Yes please wait until we marge it.

**Comment by rishika789** [comment]
> Yes please wait until we marge it.

OKAY
