### ISSUE TITLE
footer on each page

### ISSUE THREAD

**Issue by rishika789** [nilisha-jais/Musicophilia#354]
footer on each page is different. I would like to make it as in homepage.

homepage

![Screenshot (914)](https://user-images.githubusercontent.com/78673968/122452565-02f53d00-cfc7-11eb-9426-b52f7c756a62.png)

other pages

![Screenshot (915)](https://user-images.githubusercontent.com/78673968/122452592-0be60e80-cfc7-11eb-8fe0-3e50c75e3247.png)

![Screenshot (916)](https://user-images.githubusercontent.com/78673968/122452831-4bacf600-cfc7-11eb-98e6-c0ae7d77cc50.png)

**Comment by rishika789** [comment]
@nilisha-jais 
@niloysikdar

**Comment by niloysikdar** [comment]
Go ahead @rishika789

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by rishika789** [comment]
I am working on it .
