### ISSUE TITLE
button not working on login page

### ISSUE THREAD

**Issue by nitishapiplani** [nilisha-jais/Musicophilia#355]
i would like to make it working. @nilisha-jais

**Comment by nilisha-jais** [comment]
Go ahead @nitishapiplani

**Comment by RituCs** [comment]
I would like to work on this issue.

**Comment by niloysikdar** [comment]
Go ahead @RituCs

**Comment by RituCs** [comment]
Sorry for the late.I was busy for final sem exam. Can you please tell exactly what I have to do with the button in  Login Page?@niloysikdar @nilisha-jais

**Comment by harshita2216** [comment]
> Sorry for the late.I was busy for final sem exam. Can you please tell exactly what I have to do with the button in Login Page?@niloysikdar @nilisha-jais

@niloysikdar, please have a look. 
If it's working fine then we can close this issue.

**Comment by niloysikdar** [comment]
Okay @harshita2216
