### ISSUE TITLE
Add more UI features on sign in page

### ISSUE THREAD

**Issue by supzi-del** [nilisha-jais/Musicophilia#360]
## 🚀 Feature

I would like to add the following things on the sign-in page-
Cursor pointer on sign-in and sign up button
Zoom in animation on social media icons
Inner box shadow on input boxes.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

I would like to work on this under LGMSOC

**Comment by niloysikdar** [comment]
Assigned @supzi-del
