### ISSUE TITLE
Showing dance videos as cards and main playing video as popup onclick to card

### ISSUE THREAD

**Issue by ShwetKhatri2001** [nilisha-jais/Musicophilia#363]
## 🚀 Feature

We have main video and other videos on two different sides currently, instead of that we can have all videos as cards on whole page and height and main video can be seen in new popup window at center

## Pitch

Videos can be arranged and seen more properly after this

@niloysikdar I would like to work on this issue under LGM-SOC.

**Comment by niloysikdar** [comment]
Assigned @ShwetKhatri2001
