### ISSUE TITLE
add bottom to top button

### ISSUE THREAD

**Issue by royalleads15** [nilisha-jais/Musicophilia#37]
Assign this task form me and I have already did it .
![bottom to top](https://user-images.githubusercontent.com/56637948/121291359-ca3dcf80-c905-11eb-8fff-a738ef01c9f9.jpg)

**Comment by V-Yeshwanth** [comment]
Hey @nilisha-jais I can Work on this issue .

**Comment by royalleads15** [comment]
I guess you are unable to find your own ssue 😂😂

**Comment by niloysikdar** [comment]
Check #18
