### ISSUE TITLE
making the navbar identical for all the pages

### ISSUE THREAD

**Issue by ashana1647** [nilisha-jais/Musicophilia#375]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## Add relevant screenshot or video (if any)

(Add here)
the nav bars of all pages are different. All the pages must have same navbars otherwise it wont look professional.
![2021-06-20 (1)](https://user-images.githubusercontent.com/60913775/122668401-884e3c80-d1d5-11eb-8a56-351c6805b0c8.png)
![2021-06-20 (2)](https://user-images.githubusercontent.com/60913775/122668412-9439fe80-d1d5-11eb-8383-a9600d5c60b0.png)
![2021-06-20 (3)](https://user-images.githubusercontent.com/60913775/122668417-9ac87600-d1d5-11eb-89d8-85ccb75494d0.png)
![2021-06-20](https://user-images.githubusercontent.com/60913775/122668421-9f8d2a00-d1d5-11eb-983c-a86ce82876a9.png)

**Comment by nisha331** [comment]
The pr for this have been already made. @ashana1647
