### ISSUE TITLE
Improve footer 

### ISSUE THREAD

**Issue by Jagannath8** [nilisha-jais/Musicophilia#378]
## 🚀 Feature

Footer should be improved

**Comment by harishpansari** [comment]
Please assign this task to me @Jagannath8

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21. @nilisha-jais @niloysikdar

**Comment by niloysikdar** [comment]
Assigned @Jagannath8

**Comment by harshita9621** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.
