### ISSUE TITLE
Add levels in the memory game

### ISSUE THREAD

**Issue by nilisha-jais** [nilisha-jais/Musicophilia#4]
Add an easy, medium and hard level in the game where the easy level has the least number of cards and hard level the most number of cards.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by nilisha-jais** [comment]
I'll start assigning issues to all contributors from 10th June when the contribution period starts

**Comment by nilisha-jais** [comment]
@Jagannath8 go ahead. Assigning you!

**Comment by Jagannath8** [comment]
@nilisha-jais  I have a small doubt,
I have to use the existing images to build easy, medium and hard level in the game or I can add some new images.

**Comment by niloysikdar** [comment]
You can also add your own images @Jagannath8
