### ISSUE TITLE
Guess The Singer Game

### ISSUE THREAD

**Issue by shreyansh30saxena** [nilisha-jais/Musicophilia#40]
Hi there,
I'll try to make a game called "guess the singer" 
I have an idea about it and m I think I'll be able to give life to that idea using HTML,CSS and Vanilla JavaScript.
So can you please assign me this under LGM-SOC'21?

**Comment by nilisha-jais** [comment]
Go ahead @shreyansh30saxena. Assigning you!

**Comment by shreyansh30saxena** [comment]
Thankyou
On it.
