### ISSUE TITLE
The "Chatbot" and "Go to top" button are overlapping

### ISSUE THREAD

**Issue by nilisha-jais** [nilisha-jais/Musicophilia#404]

**Comment by anushruti11** [comment]
I would like to work on this issue.

**Comment by nilisha-jais** [comment]
Assigned @anushruti11

**Comment by anushruti11** [comment]
Hey! @nilisha-jais Please mention the steps to reproduce the same.

**Comment by nilisha-jais** [comment]
The is solved by someone. Try to find a new one :)
