### ISSUE TITLE
Make the Nav bar fixed

### ISSUE THREAD

**Issue by supzi-del** [nilisha-jais/Musicophilia#41]
Navbar can be fixed/sticky after scrolling down which will give a good effect.

You can assign this to me if you think it's appropriate.

**Comment by supzi-del** [comment]
And also, in the navbar, a smooth transition effect can be given when hovered upon home,about and contact us.

**Comment by niloysikdar** [comment]
There are lots of issues related to the navbar, please try to work on the other issues. @supzi-del

**Comment by supzi-del** [comment]
Oh okay! We can probably get back to this later.

**Comment by niloysikdar** [comment]
Sure @supzi-del , there are lots of other issues, hope you will find some.
