### ISSUE TITLE
Fixing the About Page

### ISSUE THREAD

**Issue by anushruti11** [nilisha-jais/Musicophilia#417]
## 🐛 Bug Report

The gif's in the cards of "About Page" are not in proper alignment. 

## Add relevant screenshot or video (if any)

![screencapture-127-0-0-1-5501-About-index-html-2021-06-22-21_44_29](https://user-images.githubusercontent.com/65386044/122962720-512d8600-d3a3-11eb-8892-99feac8fa47b.png)

**Comment by anushruti11** [comment]
@nilisha-jais Can I work on this issue?

**Comment by nilisha-jais** [comment]
There's already a pull request which fixes it!

**Comment by nitishapiplani** [comment]
is this issue open or close
if open plzz assign

**Comment by anushruti11** [comment]
> is this issue open or close
> if open plzz assign

As mentioned above there's already a pull request which fixes this issue so it's not available now.
