### ISSUE TITLE
Can Add little hover effect on box.

### ISSUE THREAD

**Issue by starrohan999** [nilisha-jais/Musicophilia#42]
Do we add a hover effect in boxes of every section on the front page? the effect will be like when we hover it, it the shadow of the border changes to pale green color.

Before
![2021-06-09 (2)](https://user-images.githubusercontent.com/71714344/121405732-03fced80-c97b-11eb-8532-0ae8edd44aaa.png)

After
![Untitled design](https://user-images.githubusercontent.com/71714344/121405748-09f2ce80-c97b-11eb-8c12-5e9f269076bb.png)

**Comment by starrohan999** [comment]
I am an LGM soc participant and please assign it to me.
@nilisha-jais  please assign it to me.

**Comment by niloysikdar** [comment]
Assigned @starrohan999 , go ahead.
