### ISSUE TITLE
Can I add database for signup and login page

### ISSUE THREAD

**Issue by jugeshraghav** [nilisha-jais/Musicophilia#426]
## 🚀 Feature

(A clear and concise description of what the feature is.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by jugeshraghav** [comment]
I would like to work on the issue

**Comment by jugeshraghav** [comment]
@niloysikdar should i use nodejs or php for the backend

**Comment by nilisha-jais** [comment]
Use node

**Comment by jugeshraghav** [comment]
I am working on it please give me time as I have exams .

**Comment by niloysikdar** [comment]
Sure @jugeshraghav , Thanks for letting us know. Finish your exams, take your time.

**Comment by harshita2216** [comment]
@jugeshraghav, any update on this?

**Comment by jugeshraghav** [comment]
hi @harshita sorry for being too late. Can I continue working on the issue.

**Comment by niloysikdar** [comment]
Do you want to continue your work on this issue @jugeshraghav ?

**Comment by jugeshraghav** [comment]
Yes, please!

**Comment by niloysikdar** [comment]
No worries, go ahead @jugeshraghav

**Comment by jugeshraghav** [comment]
I have created database using mongo compass. what do i do next ? can i deploy it as it is or i have to do something else.
@niloysikdar

**Comment by niloysikdar** [comment]
@nilisha-jais kindly look into this

**Comment by nilisha-jais** [comment]
@jugeshraghav have you used node.js MongoDB connectivity to insert and retrieve data or php MongoDB

**Comment by jugeshraghav** [comment]
Yes

**Comment by nilisha-jais** [comment]
ok then deploy it. Let's see!

**Comment by niloysikdar** [comment]
I think we don't need any kind of database for the users, I am really unable to find a use case for the database :) @nilisha-jais look into this and you can close the issue if you also think the same.

**Comment by nilisha-jais** [comment]
> I think we don't need any kind of database for the users, I am really unable to find a use case for the database :) @nilisha-jais look into this and you can close the issue if you also think the same.

Yes, I too am finding no use of it. @jugeshraghav if you wish you can implement google sign in!
