### ISSUE TITLE
Creating an account

### ISSUE THREAD

**Issue by Rishita11** [nilisha-jais/Musicophilia#43]
I would like to work on this under LGM-SOC 21. By creating an account it will be easy to recommend some songs or at least keep a track of their listening activity.

**Comment by nilisha-jais** [comment]
@Rishita11 assigned

**Comment by Rishita11** [comment]
https://rishita11.github.io/Account.github.io/ 

I have made the necessary changes. Let me know if anything else is required.

**Comment by niloysikdar** [comment]
Hey @Rishita11 , please submit a pr for the issue.

**Comment by Amrutha1101** [comment]
Can I work on this issue under LGM-SOC?
