### ISSUE TITLE
change the border color of images in Music box section.

### ISSUE THREAD

**Issue by starrohan999** [nilisha-jais/Musicophilia#44]
change the border color of images in the Music box section. and also increase  box shadow of container.
Before
![2021-06-09 (2)](https://user-images.githubusercontent.com/71714344/121407392-e03aa700-c97c-11eb-98e9-1d8eb4f7a31d.png)

After
![Untitled design](https://user-images.githubusercontent.com/71714344/121407414-e7fa4b80-c97c-11eb-8329-e029cddefadf.png)

**Comment by starrohan999** [comment]
Hey @nilisha-jais  please assign it me.

**Comment by starrohan999** [comment]
I am LGM soc-21 participant

**Comment by nilisha-jais** [comment]
Go ahead @starrohan999
