### ISSUE TITLE
Contact page is overlapping with footer

### ISSUE THREAD

**Issue by SUSHANT731** [nilisha-jais/Musicophilia#443]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)
![Screenshot (248)](https://user-images.githubusercontent.com/70851543/123209374-1f6d0a00-d4de-11eb-83f3-dd1f77f5d470.png)

## Add relevant screenshot [or](url) video (if any)

(Add here)

**Comment by SUSHANT731** [comment]
plz assign this task to me

**Comment by harshita2216** [comment]
Hey @SUSHANT731. It looks like the issue has been taken care of, hence closing this. Thanks.
