### ISSUE TITLE
miscellaneous changes.

### ISSUE THREAD

**Issue by nisha331** [nilisha-jais/Musicophilia#448]
## 🐛 Bug Report

* remove band gif from band page.(page would look better without it).
* remove footer from band page.(no other page has footer)
* add back button to lyrics finder page.
* Give Heading "All out Musicophilia " to about page. 
* add favicon in karioke page.
## Add relevant screenshot or video (if any)

(Add here)

**Comment by nisha331** [comment]
Sorry @Divyanshj i could have also given /assign and get it assigned after creating the issue but i wants the mentors and the project admin to check that the changes won't disturb the project . So i request you to unassign yourself.

**Comment by Divyanshj** [comment]
@nisha331 No problem

**Comment by RiyaGupta89** [comment]
Is this issue open, can I work on this issue?
