### ISSUE TITLE
Changes in Music Box page

### ISSUE THREAD

**Issue by drishika2002** [nilisha-jais/Musicophilia#45]
Make some changes like adding a heading and background to the page, etc to make it look more attractive.

I want to work on this issue under LGM SOC'21. Please assign this issue to me.

**Comment by niloysikdar** [comment]
Assigned @drishika2002 , go ahead.

**Comment by drishika2002** [comment]
> Assigned @drishika2002 , go ahead.

Yes, thank you very much!
