### ISSUE TITLE
Input fields in contact us page blend in the background. 

### ISSUE THREAD

**Issue by pallavi-1812** [nilisha-jais/Musicophilia#453]
## 🐛 Bug Report
Input fields in contact us page blend in the background. I would like to add beige color in input background to enhance it's look and so that it does not blend with the background image. Please assign me this issue.

## Add relevant screenshot or video (if any)
![Annotation 2021-06-25 205155](https://user-images.githubusercontent.com/67572675/123447227-3a7f6d00-d5f7-11eb-9979-d491990573ff.png)

(Add here)

**Comment by RiyaGupta89** [comment]
Can I work on this issue?

**Comment by harshita2216** [comment]
@pallavi-1812, can you also make the contact page responsive? If you can, then please edit this issue name and add that too. 
Thanks.

**Comment by Anadee11** [comment]
@harshita2216   If the issue is open to work on please edit the issue and I would like to get this one assigned and work on the contact page.

**Comment by pallavi-1812** [comment]
@harshita2216 Hey, sorry for delay, I had some issues with my laptop. I would love to work on this issue and making the contact page responsive. Can I get this issue assigned to me?

**Comment by niloysikdar** [comment]
Sure @pallavi-1812 , go ahead.
