### ISSUE TITLE
piano game

### ISSUE THREAD

**Issue by bharth-stack** [nilisha-jais/Musicophilia#454]
## 🚀 Feature

I want to add a piano game where piano makes some random sounds after starting the game and the player have the guess the sound exactly by clicking the piano buttons.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by bharth-stack** [comment]
> @bharth-stack, this issue hasn't had any activity in 3 days. It will become unassigned in 2 days to make room for someone else to contribute.

Kk I will submit it by Monday

**Comment by bharth-stack** [comment]
![Screenshot (166)](https://user-images.githubusercontent.com/74871715/124495417-b3d84600-ddd5-11eb-8b1b-d9b22d653133.png)

can't able push the project

**Comment by bharth-stack** [comment]
https://bharth-stack.github.io/Piano-game/
this is the link of project

**Comment by harshita2216** [comment]
@bharth-stack, please give us an update on this? Otherwise, we'll have to unassign you.

**Comment by bharth-stack** [comment]
reassign me today I will push

**Comment by bharth-stack** [comment]
reassign me today I will push

**Comment by niloysikdar** [comment]
Do you still want to work on this @bharth-stack ?
Then we will reassign you.

**Comment by bharth-stack** [comment]
yup I want to work on this.
