### ISSUE TITLE
Add a awesome contant us  page using css html  so can u asssign me to these!

### ISSUE THREAD

**Issue by LegendSumeet** [nilisha-jais/Musicophilia#46]
Hello, I am a LGM-SOC'21 Participant
I am a Sumeet And a beginner to open source contributions, I learnt open source contributions recently,
Assign this issue to me.

**Comment by LegendSumeet** [comment]
@nilisha-jais can u assign me to these?

**Comment by nilisha-jais** [comment]
Your issue is same as #3 .Please have a look!

**Comment by LegendSumeet** [comment]
But are they assigned to these

**Comment by nilisha-jais** [comment]
No I'll assign to the person who commented there first because that issue was created first
