### ISSUE TITLE
[Bug] Alignment of text

### ISSUE THREAD

**Issue by niloysikdar** [nilisha-jais/Musicophilia#469]
## 🐛 Bug Report

Need to center the text of the cards in y-axis.

## Add relevant screenshot or video (if any)

![Capture](https://user-images.githubusercontent.com/58071992/124071807-8e59de00-da5d-11eb-91a3-b847921791c2.PNG)

**Comment by ij007** [comment]
I would like to work in it.

**Comment by niloysikdar** [comment]
Go ahead @ij007

**Comment by ij007** [comment]
Are you satisfied with y-axis alignment of above cards (in mindful music section)?

**Comment by niloysikdar** [comment]
Yes just put the text to the center along y-axis @ij007
