### ISSUE TITLE
images and buttons over lapping out on size < 307px width;

### ISSUE THREAD

**Issue by mayankmohak** [nilisha-jais/Musicophilia#47]
The Bug
![image](https://user-images.githubusercontent.com/63801800/121456102-21ee4080-c9c3-11eb-9f65-60cd2c24dc33.png)

Solution is reducing buttons and image size to fit inside

Can you just assign me this issue.

**Comment by niloysikdar** [comment]
Assigned @mayankmohak , go ahead.
