### ISSUE TITLE
Odd color cards in About Us section

### ISSUE THREAD

**Issue by saloni-15** [nilisha-jais/Musicophilia#471]
## 🐛 Bug Report

- ### The color of the card looks different. The first card is more bright.
- ### Also, the images are not aligned to the center.
- ### Typo in Heading.

![image](https://user-images.githubusercontent.com/75828760/124093094-27482380-da75-11eb-87a2-77ad44c2e276.png)

**Comment by saloni-15** [comment]
@niloysikdar @nilisha-jais 
Assign this to me.

**Comment by niloysikdar** [comment]
Assigned @saloni-15
