### ISSUE TITLE
Adjusting the CSS for 'Contact Us' page in mobile view

### ISSUE THREAD

**Issue by SilverGraph** [nilisha-jais/Musicophilia#474]
## 🐛 Bug Report

Input fields are too short and their corresponding placeholder text are not properly visible

## Add relevant screenshot or video (if any)

![musicophilia netlify app_contact-us_contact(iPhone X)](https://user-images.githubusercontent.com/74287708/124272240-1a522f80-db5c-11eb-914b-e30f451266e0.png)

**Comment by siddhi-244** [comment]
Can I try this ?
