### ISSUE TITLE
About page is not responsive on mobile 

### ISSUE THREAD

**Issue by girija0707** [nilisha-jais/Musicophilia#475]
## Add relevant screenshot or video 
![screenshot](https://user-images.githubusercontent.com/63583646/124282126-17f5d280-db68-11eb-8b7e-304514e9a219.jpeg)

**Comment by niloysikdar** [comment]
Assigned @girija0707

**Comment by girija0707** [comment]
I'm trying this by display block, inline block as well as flex but its not working will you please suggest something

**Comment by niloysikdar** [comment]
What are you trying to achieve @girija0707 ?

**Comment by girija0707** [comment]
I was trying media queries so when we see the about page on phone the cards will appear one below the other because now the page  appears similar to laptop site

**Comment by gunjan-g** [comment]
Can I take up this issue if it's still open, please assign it to me

**Comment by girija0707** [comment]
> I was trying media queries so when we see the about page on phone the cards will appear one below the other because now the page appears similar to laptop site

Will you please suggest something for this

**Comment by gunjan-g** [comment]
Yes sure, could you show me the code you're writing for this

**Comment by nik464** [comment]
please assign this issue. I am from lgm soc.

**Comment by gunjan-g** [comment]
I think the page is already responsive, we don't need to change anything.

**Comment by siddhi-244** [comment]
I would like to try this  @niloysikdar

**Comment by niloysikdar** [comment]
Assigned @siddhi-244

**Comment by siddhi-244** [comment]
> Assigned @siddhi-244

Thanks. Will work on it.

**Comment by siddhi-244** [comment]
![IMG-20210724-WA0008](https://user-images.githubusercontent.com/69195262/126864757-d6b2dbb5-73b8-46b6-924e-d21a46e6a0a4.jpeg)
Is this okayy?

**Comment by siddhi-244** [comment]
@niloysikdar
