### ISSUE TITLE
The content of signup page is overflowing from the signup page.

### ISSUE THREAD

**Issue by jugeshraghav** [nilisha-jais/Musicophilia#476]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by jugeshraghav** [comment]
Can I work on the issue.

**Comment by priyakumari02** [comment]
Can I work on this issue

**Comment by niloysikdar** [comment]
You can make some changes on the SignUp Page if you want @jugeshraghav, but make sure to make only valid changes.

**Comment by niloysikdar** [comment]
Closing this
