### ISSUE TITLE
[LGM] Background for cards

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [nilisha-jais/Musicophilia#48]
I think we should have a background color to the cards which will make them distinguishable. 
I am a LGM SOC participant. Can you assign it to me?
![soc](https://user-images.githubusercontent.com/53310847/121466425-0d1aa880-c9d5-11eb-97a9-c5efd2fc3673.png)

**Comment by niloysikdar** [comment]
Assigned @kaiwalyakoparkar , go ahead.
