### ISSUE TITLE
Space between navbar  and  main section 

### ISSUE THREAD

**Issue by RiyaGupta89** [nilisha-jais/Musicophilia#484]
Can I add some space below the navbar as it will make things more clean and enhance user experience. I will add it in home page, login page and contact us page.

## Screenshot

![music](https://user-images.githubusercontent.com/72425181/124722374-9dda9a80-df27-11eb-9462-39ee0ab5933f.png)

**Comment by niloysikdar** [comment]
Assigned @RiyaGupta89 , go ahead.
