### ISSUE TITLE
Card hover

### ISSUE THREAD

**Issue by RiyaGupta89** [nilisha-jais/Musicophilia#486]
![card](https://user-images.githubusercontent.com/72425181/124871309-865fe800-dfe1-11eb-8f57-122001bab749.png)
On hover these card gets bigger and I think not much space is present in the page therefore to make the UI better, on hover we should have effect that makes the card look smaller. If you think this is relevant issue, please assign me this issue.

**Comment by Sejal2801** [comment]
assign it to me

**Comment by gunjan-g** [comment]
I would like to work on this issue, please assign it to me
