### ISSUE TITLE
Changed scroll bar of home page to match it with other sections

### ISSUE THREAD

**Issue by gunjan-g** [nilisha-jais/Musicophilia#504]
## 🚀 Feature
The scrollbar of other sections are different form that of home page

## Motivation
UI Design

## Pitch
To maintain consistency

## Add relevant screenshot or video (if any)
![image](https://user-images.githubusercontent.com/81305824/125206759-7d536d00-e2a6-11eb-9680-db9fd857492d.png)

![image](https://user-images.githubusercontent.com/81305824/125206770-85aba800-e2a6-11eb-9078-e8f9388b5f5c.png)

**Comment by gunjan-g** [comment]
@harshita2216 @niloysikdar please assign the label so that i can work on it

**Comment by niloysikdar** [comment]
Make the Scrollbar Green for all pages @gunjan-g .

**Comment by gunjan-g** [comment]
> Make the Scrollbar Green for all pages @gunjan-g .

sure
