### ISSUE TITLE
Fix the footer in Contact and Login page

### ISSUE THREAD

**Issue by nilisha-jais** [nilisha-jais/Musicophilia#507]
The footer in Contact page is overlapping with the content and there's extra space below the footer in Login page.

**Comment by MukulKolpe** [comment]
Hey @nilisha-jais, can I work on this issue under LGM-SOC??

**Comment by gunjan-g** [comment]
I want to work on this issue

**Comment by nilisha-jais** [comment]
@MukulKolpe commented first so he should get a chance to work. You can take any other issue @gunjan-g

**Comment by gunjan-g** [comment]
> @MukulKolpe commented first so he should get a chance to work. You can take any other issue @gunjan-g

yes ok
