### ISSUE TITLE
Unresponsive navbar

### ISSUE THREAD

**Issue by gunjan-g** [nilisha-jais/Musicophilia#509]
## 🐛 Bug Report
1. The navbar is not responsive at mobile view
2. Contact and login page don't have the same effect on toggle view

## Add relevant screenshot or video (if any)
Not responsive:
![image](https://user-images.githubusercontent.com/81305824/125312049-91a07400-e351-11eb-82da-b43d96513053.png)

Different Effects:
![image](https://user-images.githubusercontent.com/81305824/125312175-ada41580-e351-11eb-8395-f6457c06cea0.png)

![image](https://user-images.githubusercontent.com/81305824/125312240-bbf23180-e351-11eb-9498-25d084e0c354.png)

**Comment by gunjan-g** [comment]
@harshita2216 Please label the issue so I can work upon this

**Comment by nik464** [comment]
please assign this issue to me. I will surely complete this.

**Comment by harshita2216** [comment]
> please assign this issue to me. I will surely complete this.

Hey. This is already assigned at the moment. If the assigned person is unable to solve the issue for some reason, we'll be considering you next! 
Thanks, @nik464.
