### ISSUE TITLE
The band can also be played the keyboard keys.

### ISSUE THREAD

**Issue by jugeshraghav** [nilisha-jais/Musicophilia#53]
As clicking the mouse again and again is so much exhausting. We can also use the keyboard keys to play the tunes just as we do in video games.

Can I work on the issue.

**Comment by jugeshraghav** [comment]
Can I get this issue assigned? @nilisha-jais @niloysikdar

**Comment by niloysikdar** [comment]
Assigned @jugeshraghav , go ahead.

**Comment by jugeshraghav** [comment]
@niloysikdar  I created the pull request but some checks were not verified. Do I have to create the pull request again.
