### ISSUE TITLE
Text is not aligned in the card on hovering

### ISSUE THREAD

**Issue by aashimawadhwa** [nilisha-jais/Musicophilia#533]
When hovering on the card the text on the front side of the card is mirrored on the back side of card and is not readable and does not look presentable.

![Screenshot from 2021-07-26 23-26-19](https://user-images.githubusercontent.com/73706697/127036077-b6c31302-34bb-40fb-90a0-c07b6176d445.png)

Assign this issue to me please , I want to work on it  under LGMSOC'21.

**Comment by Cartikx3** [comment]
please assign this to me

**Comment by aashimawadhwa** [comment]
I'm already working on it @Cartikx3
