### ISSUE TITLE
ABOUT PAGE OF WEBSITE

### ISSUE THREAD

**Issue by Ishigupta08** [nilisha-jais/Musicophilia#56]
## 🚀 Feature

(about page is designed with html,css)

## Motivation

(Without enrich about page user cannot get to know what all we have in our web)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by Ishigupta08** [comment]
plzz assign me this issue/assign

**Comment by vipul-04** [comment]
please add me in this issue

**Comment by niloysikdar** [comment]
@Ishigupta08 , @vipul-04 , please check #1

**Comment by Ishigupta08** [comment]
i can't find any @niloysikdar

**Comment by vipul-04** [comment]
I guess this issue assigned to someone else...

**Comment by niloysikdar** [comment]
Check issue #1 , there is already an open issue related to the same @vipul-04
