### ISSUE TITLE
background of piano cover

### ISSUE THREAD

**Issue by Ishigupta08** [nilisha-jais/Musicophilia#57]
## 🚀 Feature

(A clear and concise description of what the feature is.)

## Motivation

(background is not looking preety as it sounds)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by Ishigupta08** [comment]
plzz assign me @nilisha-jais

**Comment by niloysikdar** [comment]
Please describe the issue @Ishigupta08 , otherwise, we can't assign you.

**Comment by Ishigupta08** [comment]
issue is that look and feel of website pino cover is not good
@niloysikdar

**Comment by niloysikdar** [comment]
@Ishigupta08 please add a screenshot for the same which you want to fix.

**Comment by Ishigupta08** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/78248931/121522317-9d2b1300-ca12-11eb-87a5-8997b856b2b3.png)

**Comment by niloysikdar** [comment]
Assigned @Ishigupta08 , go ahead.
