### ISSUE TITLE
In Footer section there is No year mention related to Copyright.

### ISSUE THREAD

**Issue by starrohan999** [nilisha-jais/Musicophilia#63]
## 🐛 Bug Report

In the Footer section, there is No year mention related to Copyright.

## Add relevant screenshot or video (if any)
![2021-06-10 (4)_LI](https://user-images.githubusercontent.com/71714344/121488180-765be500-c9f0-11eb-8815-150dec911744.jpg)

**Comment by starrohan999** [comment]
@nilisha-jais 
please assign it to me.

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by ambivert-sam** [comment]
Hey, @starrohan999 I'm a participant of LGMSOC'21 I would like to contribute to this issue will you please assign it to me

**Comment by niloysikdar** [comment]
Assigned @starrohan999 , go ahead.

**Comment by starrohan999** [comment]
Thank you @niloysikdar 
I will give my best.

**Comment by starrohan999** [comment]
Actually, I am confused, please help me.
1. © 2021 | Nilisha | All rights reserved.
2. © 2021 | Musicophilia | All rights reserved.

which one is correct 1 or 2? 
please tell me @niloysikdar @nilisha-jais .

**Comment by aditya687** [comment]
I want to contribute in this issue for LGMSOC'21 . Please assign me in this work
@niloysikdar
