### ISSUE TITLE
Adding Favicon

### ISSUE THREAD

**Issue by nisha331** [nilisha-jais/Musicophilia#65]
## 🚀 Feature

As there is no favicon I would like to add it. 

## Add relevant screenshot or video (if any)

![Capture m](https://user-images.githubusercontent.com/76838660/121489003-4103c700-c9f1-11eb-8a5a-4f448ac8ca18.PNG)

As the coding period for LGMSOC starts I would like to work on this issue, mentor and Project admins it would be great if you could assign this to me.

**Comment by niloysikdar** [comment]
@nisha331 , check issue #14 , if you are interested to work on that issue, you can comment there.

**Comment by nisha331** [comment]
Oh thank you @niloysikdar  , commented there. Kindly check it out.
