### ISSUE TITLE
Adjusting the width of the Band Page

### ISSUE THREAD

**Issue by utkarshgoel10** [nilisha-jais/Musicophilia#66]
The whole width of the Band page can be reduced to make it look more beautiful, appealing, and responsive.

**Comment by utkarshgoel10** [comment]
Please assign me with this issue @nilisha-jais

**Comment by niloysikdar** [comment]
Please attach the screenshots @utkarshgoel10

**Comment by utkarshgoel10** [comment]
![image](https://user-images.githubusercontent.com/66838142/121539264-26e2dc80-ca23-11eb-8154-9bf04c86b2be.png)
I'm asking to do something like this.

And furthermore, can I make this page responsive too, for the mobile devices.

**Comment by niloysikdar** [comment]
Assigned @utkarshgoel10 , go ahead.
