### ISSUE TITLE
Adding light background to the cards on the home page

### ISSUE THREAD

**Issue by shriya030** [nilisha-jais/Musicophilia#67]
## 🚀 Feature

I want to add light background to these cards so that the text and border of the cards and the background image are clearly visible.
I will add a background and keep its opacity low for better viewing.

Kindly assign me this issue as a part of LGMSOC21

![image](https://user-images.githubusercontent.com/56861600/121489874-22ea9680-c9f2-11eb-925c-534aabb0b522.png)

**Comment by niloysikdar** [comment]
There are few open issues regarding the changing of style of the cards @shriya030
