### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by SanjeevKumar22** [nilisha-jais/Musicophilia#68]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Add a dark mode and light mode
## Motivation

(Please outline the motivation for the proposal.)
it will look nice
![Screenshot 2021-06-10 135547](https://user-images.githubusercontent.com/74849833/121491455-980a9b80-c9f3-11eb-8d1d-0a5638d60fa0.png)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by niloysikdar** [comment]
The website is currently having dark mode @SanjeevKumar22
