### ISSUE TITLE
Updating Readme file

### ISSUE THREAD

**Issue by akshatvirmani** [nilisha-jais/Musicophilia#7]
I would like to work on this issue. Please assign this to me under LGM SOC.

**Comment by akshatvirmani** [comment]
Can I work on this issue?

**Comment by starrohan999** [comment]
I made this logo for the website. 
![Blue and White Gaming Logo (1)](https://user-images.githubusercontent.com/71714344/121530492-1d557680-ca1b-11eb-8278-0afde76909fd.png)

**Comment by starrohan999** [comment]
please include this in readme file.

**Comment by namratadas1** [comment]
May I work on this issue?

**Comment by niloysikdar** [comment]
Hey @starrohan999 , I have opened an issue regarding the adding of a logo.

**Comment by niloysikdar** [comment]
@starrohan999 , please see #91

**Comment by niloysikdar** [comment]
Assigned @akshatvirmani , go ahead.
