### ISSUE TITLE
can I add new content 

### ISSUE THREAD

**Issue by bharth-stack** [nilisha-jais/Musicophilia#73]
## 🚀 Feature

It will show singers details and history about him/her.

## Pitch

it will help the user to find the singer details.

## Add relevant screenshot or video (if any)
![Screenshot (141)](https://user-images.githubusercontent.com/74871715/121509165-ff304c00-ca03-11eb-8448-7f1f97d704a8.png)

but after adding little bit css it will look similar to the project website it just for idea to  understand

**Comment by bharth-stack** [comment]
I am LGM  participant

**Comment by niloysikdar** [comment]
Assigned @bharth-stack , go ahead.
