### ISSUE TITLE
Add a New Game under the Rollick games section

### ISSUE THREAD

**Issue by vimalprogrammer** [nilisha-jais/Musicophilia#75]
## 🚀 Feature

Add a Rock, Paper, Scissors Game under the Rollick Games section.

## Pitch

The familiar game of Rock, Paper, Scissors is played like this: at the same time, two players display one of three symbols: a rock, paper, or scissors. Rock beats scissors, scissors beat paper by cutting it, and paper beats rock by covering it, if both are the same it results in a tie. The computer simply chose randomly with an equal probability for each object.

## Add relevant screenshot or video (if any)

![RPS game](https://user-images.githubusercontent.com/76787061/121530100-b20ba480-ca1a-11eb-8a10-0d84a46e70ae.jpeg)

The UI of the game is described above...

Please assign me to contribute this feature under the LGMSOC

**Comment by nilisha-jais** [comment]
I don't think the game matches with the theme of the website ,i.e., music. Think of something related to music or has the theme of music

**Comment by vimalprogrammer** [comment]
Yeah, You're right! now only I take a brief look into the project. Sorry, it's my bad. Thank You : )
