### ISSUE TITLE
[LGM] Music Card Layout

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [nilisha-jais/Musicophilia#78]
## Motivation

While seeing into the music section I found out that the music card is not so appealing. I would like to make it more user catchy.

## Pitch

The changes are as follows. The card looks like ( one given as before) which is wider and does not suit the theme of the application. I would like to change it to like (one given in after). Could you please assign it to me?

## Before:
![before](https://user-images.githubusercontent.com/53310847/121543538-9dcda480-ca26-11eb-8fbb-a2773fc1db7e.png)

## After:
![after](https://user-images.githubusercontent.com/53310847/121543546-a02ffe80-ca26-11eb-8173-0d6cc61cf90f.png)

**Comment by kaiwalyakoparkar** [comment]
@niloysikdar This is a small issue and won't take much time. What should I do?

**Comment by nilisha-jais** [comment]
You can take it now @kaiwalyakoparkar

**Comment by niloysikdar** [comment]
You can work on the issue @kaiwalyakoparkar , but try to solve the already assigned issues first for the best practice.

**Comment by kaiwalyakoparkar** [comment]
@niloysikdar Yup did all in the assignment sequence. :)
