### ISSUE TITLE
Adding more songs in music box.

### ISSUE THREAD

**Issue by akshatvirmani** [nilisha-jais/Musicophilia#8]
I would like to work on this issue. Please assign this to me under LGM SOC.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by Atif0604** [comment]
I wanna add more songs to it 
Please assign it to me 
I'm a participant of LGM SOC-21.
@nilisha-jais

**Comment by akitiashritha** [comment]
I would like to add some more songs 
please assign it to me under LGM SOC.!

**Comment by niloysikdar** [comment]
Assigned @akitiashritha , go ahead.

**Comment by akshatvirmani** [comment]
Can I work on this issue?

**Comment by niloysikdar** [comment]
If the currently assigned participant is unable to complete within the given time period then definitely you can @akshatvirmani
