### ISSUE TITLE
Social Media Engagement Buttons

### ISSUE THREAD

**Issue by Shaishav0507** [nilisha-jais/Musicophilia#84]
## 🚀 Feature

I would like to add Social Media buttons where person can feel like contacting you or just have a glimpse of your social handles.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Add relevant screenshot or video (if any)

(Add here)

**Comment by niloysikdar** [comment]
Check issue #17 . This is a duplicate one.
