### ISSUE TITLE
Making the questions of the Music Quiz dynamic

### ISSUE THREAD

**Issue by niloysikdar** [nilisha-jais/Musicophilia#88]
## 🚀 Feature

Currently, all of the questions of the music quiz are hardcoded and static. We can use [this API](https://opentdb.com/api_config.php) to make the questions dynamic.

**Comment by pallavi-1812** [comment]
Hello! Can I work on this issue?

**Comment by nilisha-jais** [comment]
Go ahead @pallavi-1812
