### ISSUE TITLE
Adding a chatbot

### ISSUE THREAD

**Issue by namratadas1** [nilisha-jais/Musicophilia#89]
## 🚀 Feature

The ChatBot will provide the user- information about different types of music and will also provide them with resources to learn music.

**Comment by namratadas1** [comment]
May I work on this?

**Comment by namratadas1** [comment]
@niloysikdar I am still training the chatbot. May I get 1 day more?

**Comment by niloysikdar** [comment]
Try to complete it asap @namratadas1
