### ISSUE TITLE
Adding new instrument images in band

### ISSUE THREAD

**Issue by akshatvirmani** [nilisha-jais/Musicophilia#9]
I would like to work on this issue. Please assign this to me under LGM SOC.

**Comment by rvandana193** [comment]
I would like to work on this project. I am a participant im LGM-SOC.

**Comment by akshatvirmani** [comment]
Can I work on this issue?

**Comment by nilisha-jais** [comment]
Which images do you wish to change. The gif or the band components @akshatvirmani

**Comment by akshatvirmani** [comment]
Band components

**Comment by Sumit11081996** [comment]
@nilisha-jais assign this issue
