### ISSUE TITLE
Need a Logo for the website

### ISSUE THREAD

**Issue by niloysikdar** [nilisha-jais/Musicophilia#91]
## 🚀 Feature

Need an awesome logo for the website.

This is an open issue, we aren't going to assign anyone for this issue. You can submit your logo in this thread and we will choose the best one and going to add it to our website.

**Comment by nisha331** [comment]
I as a LGMSOC would like to work on it could you assign this issue to me.

**Comment by aum-singhal** [comment]
Hello Sir.

Can I contribute in this issue.
I am a participant of LGM-SOC.
If possible please assign it to me.

Thanks 😊

**Comment by Nikhita28** [comment]
I'd like to work on this as a participant of LGMSOC '21.

**Comment by niloysikdar** [comment]
This is an open issue, we aren't going to assign anyone for this issue. You can submit your logo in this thread and we will choose the best one and going to add it to our website. @nisha331  @aum-singhal @Nikhita28

**Comment by starrohan999** [comment]
Here are two designs that I have made.
![Blue and White Gaming Logo (1)](https://user-images.githubusercontent.com/71714344/121646054-8805c100-cab2-11eb-823f-fc8d2a8a9965.png)
![Blue and White Gaming Logo](https://user-images.githubusercontent.com/71714344/121646092-9358ec80-cab2-11eb-8821-dea3a47de317.png)

@niloysikdar and @nilisha-jais  please look at this.

**Comment by Nikhita28** [comment]
I have come up with these.
![μSICOPHILIA (1)](https://user-images.githubusercontent.com/73106734/121646349-da46e200-cab2-11eb-865e-20b272ff05d7.png)
![μSICOPHILIA](https://user-images.githubusercontent.com/73106734/121646355-dc10a580-cab2-11eb-9643-7e66261291d9.png)
![μSICOPHILIA (2)](https://user-images.githubusercontent.com/73106734/121646359-dca93c00-cab2-11eb-810a-80713bd41224.png)

**Comment by souvikrajsingh** [comment]
Sir, I want to work on this as an LGM participant, kindly assign it to me.

**Comment by starrohan999** [comment]
@souvikrajsingh please show your design in this thread @niloysikdar  decide which logo is best and then they assigned it to that contributor

**Comment by nisha331** [comment]
![Copy of Add a heading](https://user-images.githubusercontent.com/76838660/121660271-c1ddc400-cac0-11eb-8515-34cbefe9fe05.png)
![Copy of Add a heading](https://user-images.githubusercontent.com/76838660/121660641-12edb800-cac1-11eb-8eb0-396e73cc280d.png)

These are the few designed i have tried out . kindly check it.

**Comment by Abhishek-Sahoo** [comment]
![Musicophilia (1)](https://user-images.githubusercontent.com/61592628/121660888-44ff1a00-cac1-11eb-9054-9437a9b46cf6.png)

**Comment by tjanhvi** [comment]
Here the design that I have made
![image](https://user-images.githubusercontent.com/78703730/121661072-724bc800-cac1-11eb-826a-80c7a3b770a3.png)

**Comment by Abhishek-Sahoo** [comment]
![Musicophilia (2)](https://user-images.githubusercontent.com/61592628/121661191-94454a80-cac1-11eb-904f-9ea7467b7618.png)

**Comment by tjanhvi** [comment]
Here the design that I have made
![image](https://user-images.githubusercontent.com/78703730/121661232-9f987600-cac1-11eb-9097-21198a949125.png)

**Comment by aum-singhal** [comment]
White Themed

![Logo(white)](https://user-images.githubusercontent.com/69421286/121662942-87295b00-cac3-11eb-9859-35a579ee5981.png)

Black Themed 

![Logo(black)](https://user-images.githubusercontent.com/69421286/121662972-8ee8ff80-cac3-11eb-997c-464f68724bc8.png)

**Comment by nilisha-jais** [comment]
All the logos are amazing! Let @niloysikdar only decide.
(I liked @Nikhita28 's logo the most)

**Comment by starrohan999** [comment]
![Blue and White Gaming Logo (2)](https://user-images.githubusercontent.com/71714344/121669380-e25e4c00-cac9-11eb-866a-4b4fe9e02d08.png)

**Comment by starrohan999** [comment]
there are two more @niloysikdar and @nilisha-jais  I hope you liked it.
![Blue and White Gaming Logo (4)](https://user-images.githubusercontent.com/71714344/121670724-5f3df580-cacb-11eb-8393-b86304efe2e2.png)
![Blue and White Gaming Logo (3)](https://user-images.githubusercontent.com/71714344/121670731-606f2280-cacb-11eb-85b5-d985dda5718f.png)

**Comment by starrohan999** [comment]
sorry for the spelling mistake I will correct it.

**Comment by mrunankpawar** [comment]
I would like to solve this issue. It would be great if I get this issue assigned to me.

**Comment by starrohan999** [comment]
![USICOPHILIA (1)](https://user-images.githubusercontent.com/71714344/121719767-967ac980-cb00-11eb-8761-f0642a9723f4.png)
![USICOPHILIA](https://user-images.githubusercontent.com/71714344/121719784-97abf680-cb00-11eb-924b-9c862dfcd48b.png)

**Comment by starrohan999** [comment]
corrected version

**Comment by starrohan999** [comment]
is any logo is final out for website @niloysikdar @nilisha-jais

**Comment by niloysikdar** [comment]
@nilisha-jais kindly have a look at the new entries.

**Comment by Manasa2811** [comment]
![Musicophilia (1)](https://user-images.githubusercontent.com/57994923/121768145-31fc5080-cb7a-11eb-8aae-4400a51d8f8f.png)
![Musicophilia](https://user-images.githubusercontent.com/57994923/121768146-34f74100-cb7a-11eb-9a67-341b17db6584.png)

**Comment by nilisha-jais** [comment]
@niloysikdar choose one between @Nikhita28 's and the last entry by @starrohan999 !

**Comment by niloysikdar** [comment]
I think the last two logos of @Nikhita28 are perfect for both dark and light themes. @Nikhita28 assigned you the issue. Please make a PR for the same with those logos.
