### ISSUE TITLE
Improvement in UI in the memory game 

### ISSUE THREAD

**Issue by Amit-45** [nilisha-jais/Musicophilia#95]
## 🐛 Bug Report

The memory game  page : 

I can improve the User Interface of the page by providing a good background and by making the buttons(easy, medium , hard) more interactive with colors , borders and animation .

Please assign me this issue under LGMSOC'21 .

## Screenshot :
![Screenshot (166)](https://user-images.githubusercontent.com/77204104/121636074-fb083b00-caa4-11eb-8d7d-d575750460fd.png)

**Comment by Amit-45** [comment]
Is it under LGMSOC ?

**Comment by nilisha-jais** [comment]
Yes go ahead @Amit-45

**Comment by Amit-45** [comment]
Hey @nilisha-jais  did you just forget to assign the tag of LGMSOC to this #95 issue or  will  it be only provided if the pull request is merged?
