### ISSUE TITLE
Update Footer Copyrights notice

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [nilisha-jais/Musicophilia#98]
## 🐛 Bug Report

The footer notice for Copyrights can be updated to more precise form. One like in the MIT license added

## Add relevant screenshot or video (if any)

![cc](https://user-images.githubusercontent.com/53310847/121641653-124b2680-caad-11eb-9d55-3b5e67c45437.png)

**Comment by niloysikdar** [comment]
Assigned @kaiwalyakoparkar , go ahead.
