### ISSUE TITLE
Change color of the band title

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [nilisha-jais/Musicophilia#99]
## Motivation

The title in the band page does not have the correct color to match the theme of the application. I would like to change it to the matching theme

## Add relevant screenshot or video (if any)

![band](https://user-images.githubusercontent.com/53310847/121641982-82f24300-caad-11eb-9b5d-eb6c0ac4e06b.png)

**Comment by niloysikdar** [comment]
Assigned @kaiwalyakoparkar , go ahead.
